import type { Page } from 'puppeteer';
import { DIRECTION_ATTR } from './selectors.ts';

/**
 * The in-page half of every scraper in this service.
 *
 * Its whole job is to hand one container's markup back to Node. No finding, no
 * filtering, no interpretation — all of that lives in `parsers/`, where it can
 * be tested against a fixture with no browser and no Facebook account.
 *
 * Both functions are sent as raw strings rather than function references on
 * purpose: `tsx`'s dev transform wraps named local functions in a `__name`
 * helper that exists only in this Node process, while `page.evaluate`
 * serialises a function argument with `.toString()` to run in the page's own
 * context where that helper was never defined. `apps/ig-bridge` confirmed live
 * that this breaks message detection outright.
 */
export async function readContainerHtml(page: Page, selectors: readonly string[]): Promise<string | null> {
  return await page.evaluate(`
    (function () {
      var selectors = ${JSON.stringify(selectors)};
      for (var i = 0; i < selectors.length; i++) {
        var el = document.querySelector(selectors[i]);
        if (el) return el.outerHTML;
      }
      return null;
    })();
  `).catch(() => null) as string | null;
}

/**
 * The same, plus the one fact about a Business Suite message that markup alone
 * cannot carry: which way it went.
 *
 * Business Suite states direction purely as layout. The wrapper above an
 * inbound bubble computes `justify-content: flex-start`, an outbound one
 * `flex-end` — a computed style, resolved from a stylesheet, and therefore
 * absent from `outerHTML` no matter how much of it is serialised. So this
 * measures it here, where a browser exists, and stamps the answer onto the
 * clone. The parser then reads an ordinary attribute and stays pure.
 *
 * WHY NOT THE CLASS NAME. The two wrappers differ by exactly one atomic class
 * (`x1nhvcw1` inbound, `x13a6bvl` outbound, at the time of writing). Those
 * hashes are regenerated by Facebook's own build, and keying on one would fail
 * silently and catastrophically when it rotates: every agent reply would be
 * filed as something the customer said, then shown back to the next agent as an
 * unanswered enquiry.
 *
 * THE LIVE DOM IS NOT TOUCHED. Everything is stamped on a deep clone, which is
 * also why the two node lists line up by index — `cloneNode(true)` preserves
 * document order exactly, so the nth message in the clone is the nth message in
 * the page.
 *
 * A bubble whose ancestors report neither value is left unstamped, and the
 * parser drops and counts it. That is the safe direction: a dropped message is
 * visible in `unknownSenderRows`, a misattributed one is visible nowhere.
 */
export async function readAnnotatedContainerHtml(
  page: Page, selectors: readonly string[], messageSelector: string,
): Promise<string | null> {
  return await page.evaluate(buildAnnotatorScript(selectors, messageSelector))
    .catch(() => null) as string | null;
}

/**
 * The measurement itself: which computed `justify-content` means which
 * direction.
 *
 * Kept as data rather than written into the script as two `if`s so a test can
 * assert both the mapping and the fact that the script really embeds this
 * table. The in-page half cannot import anything, so this is the only way the
 * rule is stated once instead of twice — and two copies of a rule like this one
 * drifting apart is exactly how an agent's reply ends up filed as the
 * customer's.
 *
 * Read off the live site: an inbound bubble's nearest laid-out ancestor
 * computes `flex-start`, an outbound one `flex-end`.
 */
export const JUSTIFY_DIRECTION = {
  'flex-start': 'inbound',
  'flex-end': 'outbound',
} as const;

/**
 * The in-page program, as source. Exported so it can be inspected in a test
 * without a browser: there is no other way to prove that what actually runs on
 * the page carries the mapping above.
 */
export function buildAnnotatorScript(selectors: readonly string[], messageSelector: string): string {
  return `
    (function () {
      var selectors = ${JSON.stringify(selectors)};
      var directions = ${JSON.stringify(JUSTIFY_DIRECTION)};
      var container = null;
      for (var i = 0; i < selectors.length; i++) {
        container = document.querySelector(selectors[i]);
        if (container) break;
      }
      if (!container) return null;

      var clone = container.cloneNode(true);
      var live = container.querySelectorAll(${JSON.stringify(messageSelector)});
      var copies = clone.querySelectorAll(${JSON.stringify(messageSelector)});

      for (var j = 0; j < live.length && j < copies.length; j++) {
        var direction = null;
        for (var node = live[j]; node && node !== document.body; node = node.parentElement) {
          var justify = window.getComputedStyle(node).justifyContent;
          if (directions[justify]) { direction = directions[justify]; break; }
        }
        if (direction) copies[j].setAttribute(${JSON.stringify(DIRECTION_ATTR)}, direction);
      }

      return clone.outerHTML;
    })();
  `;
}
