import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { FastifyInstance } from 'fastify';
import { env, type Env } from '@kirana/core';
import {
  withTenant, ensureMessengerBridgeChannel, getFbBridgeConnection, setFbBridgeConnection,
  type Database,
} from '@kirana/db';
import { buildApp } from '../apps/api/src/app.ts';
import { processInboundWebhook } from '../apps/worker/src/processors/inboundNormalise.ts';
import {
  parseBusinessSuiteTranscript, parseBusinessSuiteThread, countOwnBusinessSuiteMessages,
  parseBusinessSuiteHeaderName,
} from '../apps/fb-bridge/src/parsers/businessSuiteThread.ts';
import { parseMessengerThread, selectBackfill } from '../apps/fb-bridge/src/parsers/messengerThread.ts';
import { buildAnnotatorScript, JUSTIFY_DIRECTION } from '../apps/fb-bridge/src/pageHtml.ts';
import { businessSuiteTransport } from '../apps/fb-bridge/src/transport/businessSuite.ts';
import { messengerDotComTransport } from '../apps/fb-bridge/src/transport/messengerDotCom.ts';
import { DIRECTION_ATTR } from '../apps/fb-bridge/src/selectors.ts';
import { freshDb, makeTenant, TEST_KEK, type TestTenant } from './helpers/db.ts';

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), 'fixtures', 'facebook');
const fixture = (name: string) => readFile(join(FIXTURES, name), 'utf8');

const PAGE = { id: '900000000000001', name: 'Toko Demo', assetId: '1000000000000000' };
const CONTACT = { id: '100000000000009', name: 'Sinta' };

/**
 * A Page's inbox is a different Facebook surface from a person's, and this file
 * is where that claim is held to account.
 *
 * Nothing here touches Facebook. The parser runs against a synthetic fixture
 * whose structure was read off the live site; the ingest path runs against a
 * real migrated database. The one thing that genuinely cannot be tested without
 * a browser — reading a computed style — is confined to a single function, and
 * what is tested here is that the rule it applies is stated in one place and
 * really embedded in what runs on the page.
 */

/* ------------------------------------------------ the measurement layer */

describe('measuring which way a Business Suite message went', () => {
  it('reads flex-start as inbound and flex-end as outbound', () => {
    expect(JUSTIFY_DIRECTION['flex-start']).toBe('inbound');
    expect(JUSTIFY_DIRECTION['flex-end']).toBe('outbound');
  });

  it('puts that same table into the program that actually runs on the page', () => {
    // The in-page half cannot import anything, so the rule is interpolated
    // rather than shared. This is what stops the two copies drifting apart —
    // and a drifted copy files an agent's reply as the customer's.
    const script = buildAnnotatorScript(['div[role="region"]'], '[data-message-id]');
    expect(script).toContain(JSON.stringify(JUSTIFY_DIRECTION));
    expect(script).toContain(JSON.stringify(DIRECTION_ATTR));
  });

  it('never keys on a Facebook class hash', () => {
    // `x1nhvcw1` and `x13a6bvl` were the two atomic classes that differed
    // between an inbound and an outbound wrapper on the day this was probed.
    // They are regenerated by Facebook's own build, so neither may appear.
    const script = buildAnnotatorScript(['div[role="region"]'], '[data-message-id]');
    expect(script).not.toMatch(/\bx[0-9a-z]{6,8}\b/);
  });

  it('annotates a copy, never the live page', () => {
    const script = buildAnnotatorScript(['div[role="region"]'], '[data-message-id]');
    expect(script).toContain('cloneNode(true)');
    expect(script.match(/setAttribute/g)).toHaveLength(1);
    expect(script).toMatch(/copies\[j\]\.setAttribute/);
  });
});

/* ------------------------------------------------------------- parsers */

describe('the Business Suite transcript parser', () => {
  it('takes direction from the stamp and nothing else', async () => {
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {
      contactName: CONTACT.name, selfName: PAGE.name,
    });

    expect(parsed.messages.map((m) => m.direction)).toEqual(['inbound', 'outbound', 'inbound']);
  });

  it('does not confuse an outbound message with an inbound one of identical text', async () => {
    // The fixture says "halo kak" twice, once each way. Anything keyed on the
    // words rather than on the stamp collapses these two.
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {
      contactName: CONTACT.name, selfName: PAGE.name,
    });
    const halo = parsed.messages.filter((m) => m.text === 'halo kak');

    expect(halo).toHaveLength(2);
    expect(halo.map((m) => m.direction)).toEqual(['inbound', 'outbound']);
    expect(new Set(halo.map((m) => m.externalMessageId)).size).toBe(2);
  });

  it('drops a message the measurement could not read, and says how many', async () => {
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {
      contactName: CONTACT.name, selfName: PAGE.name,
    });

    expect(parsed.messages.map((m) => m.text)).not.toContain('ini tidak boleh ikut masuk');
    expect(parsed.unknownSenderRows).toBe(1);
  });

  it('keeps Facebook\'s own message id, in the shape messenger.com also uses', async () => {
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {});

    expect(parsed.messages.every((m) => m.externalMessageId?.startsWith('mid.$'))).toBe(true);
    // The shared shape is the whole reason one idempotency key covers both
    // surfaces: the same conversation read from either cannot be stored twice.
    expect(parsed.messages[0]!.externalMessageId).toBe('mid.$cAAQAAsynthetic0001');
  });

  it('names the sender from the conversation, because the bubbles name nobody', async () => {
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {
      contactName: CONTACT.name, selfName: PAGE.name,
    });

    expect(parsed.messages[0]!.senderName).toBe(CONTACT.name);
    expect(parsed.messages[1]!.senderName).toBe(PAGE.name);
  });

  it('reads the timestamp off the group wrapper', async () => {
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {});

    expect(parsed.messages[0]!.sentAt).toBe(new Date(1758546240 * 1000).toISOString());
  });

  it('skips a sticker rather than ingesting a blank message', async () => {
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {});

    expect(parsed.messages.every((m) => m.text.trim().length > 0)).toBe(true);
    // The empty bubble is not a failure either — it must not inflate the count
    // that tells an operator the selectors went stale.
    expect(parsed.unknownSenderRows).toBe(1);
  });

  it('hands the live watcher inbound only', async () => {
    const parsed = parseBusinessSuiteThread(await fixture('business-suite-thread.html'), {
      contactName: CONTACT.name, selfName: PAGE.name,
    });

    expect(parsed.messages.map((m) => m.text)).toEqual(['halo kak', 'mau tanya harga']);
    expect(parsed.outboundRows).toBe(1);
  });

  it('reads the contact name out of the conversation header', () => {
    const header = '<span data-surface="/bizweb:inbox/lib:inbox:detail_view_header">'
      + '<div>Sinta</div><div>Assign this conversation</div></span>';

    expect(parseBusinessSuiteHeaderName(header)).toBe('Sinta');
  });
});

describe('confirming a Business Suite send', () => {
  it('counts only our own messages carrying exactly that text', async () => {
    const html = await fixture('business-suite-thread.html');

    expect(countOwnBusinessSuiteMessages(html, { text: 'halo kak' })).toBe(1);
    expect(countOwnBusinessSuiteMessages(html, { text: 'mau tanya harga' })).toBe(0);
    expect(countOwnBusinessSuiteMessages(html, { text: 'belum pernah dikirim' })).toBe(0);
  });

  it('is a count, so success needs a NEW bubble rather than a matching one', async () => {
    const html = await fixture('business-suite-thread.html');
    const before = countOwnBusinessSuiteMessages(html, { text: 'halo kak' });
    // A second identical reply arrives. "Is our text on screen?" was already
    // true before it was sent; only the count moving proves anything.
    const after = countOwnBusinessSuiteMessages(
      html.replace(
        `<div data-message-id="mid.$cAAQAAsynthetic0003" ${DIRECTION_ATTR}="inbound">mau tanya harga</div>`,
        `<div data-message-id="mid.$cAAQAAsynthetic0006" ${DIRECTION_ATTR}="outbound">halo kak</div>`,
      ),
      { text: 'halo kak' },
    );

    expect(before).toBe(1);
    expect(after).toBe(2);
  });
});

describe('reconciling a Business Suite thread more than once', () => {
  it('imports nothing the second time', async () => {
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {
      contactName: CONTACT.name, selfName: PAGE.name,
    });

    const stored = new Set<string>();
    const first = selectBackfill(parsed.messages, { isKnown: (id) => stored.has(id), maxMessages: 50 });
    for (const m of first) stored.add(m.externalMessageId!);
    const second = selectBackfill(parsed.messages, { isKnown: (id) => stored.has(id), maxMessages: 50 });

    expect(first).toHaveLength(3);
    expect(second).toHaveLength(0);
  });

  it('imports only what is genuinely new when the thread grows', async () => {
    const html = await fixture('business-suite-thread.html');
    const before = parseBusinessSuiteTranscript(html, {});
    const stored = new Set(before.messages.map((m) => m.externalMessageId!));

    const grown = parseBusinessSuiteTranscript(
      html.replace(
        '    </div>\n  </div>\n</div>',
        '      <div data-utime="1758546540"><div><div><div><div>'
        + `<div data-message-id="mid.$cAAQAAsynthetic0007" ${DIRECTION_ATTR}="inbound">masih ada?</div>`
        + '</div></div></div></div></div>\n    </div>\n  </div>\n</div>',
      ),
      {},
    );
    const missing = selectBackfill(grown.messages, { isKnown: (id) => stored.has(id), maxMessages: 50 });

    expect(missing.map((m) => m.text)).toEqual(['masih ada?']);
  });
});

/* ---------------------------------------------------------- transports */

describe('choosing a transport', () => {
  it('builds Business Suite URLs from the asset id, never the Page id', () => {
    const ctx = { pageName: PAGE.name, assetId: PAGE.assetId };

    expect(businessSuiteTransport.inboxUrl(ctx)).toContain(`asset_id=${PAGE.assetId}`);
    expect(businessSuiteTransport.inboxUrl(ctx)).not.toContain(PAGE.id);
    expect(businessSuiteTransport.threadUrl(ctx, CONTACT.id))
      .toBe('https://business.facebook.com/latest/inbox/all'
        + `?asset_id=${PAGE.assetId}&selected_item_id=${CONTACT.id}&thread_type=FB_MESSAGE`);
  });

  it('refuses to navigate at all without an asset id', () => {
    // Better one loud error at the first navigation than a browser sitting on a
    // valid-looking Business Suite page holding nobody's conversations.
    expect(() => businessSuiteTransport.inboxUrl({ pageName: PAGE.name, assetId: null }))
      .toThrow(/asset id/i);
  });

  it('says out loud that it cannot enumerate an inbox', () => {
    expect(businessSuiteTransport.discoversConversations).toBe(false);
    expect(messengerDotComTransport.discoversConversations).toBe(true);
  });

  it('leaves the messenger.com transport exactly as it was', async () => {
    const ctx = { pageName: PAGE.name, assetId: null };
    expect(messengerDotComTransport.inboxUrl(ctx)).toBe('https://www.facebook.com/messages/t/');
    expect(messengerDotComTransport.threadUrl(ctx, CONTACT.id))
      .toBe(`https://www.facebook.com/messages/t/${CONTACT.id}/`);

    // And it still reads the old fixture the way it always did — the Page work
    // must not have quietly changed what a personal inbox parses to.
    const html = await fixture('messenger-thread.html');
    const viaTransport = messengerDotComTransport.parseThread(html, { selfName: PAGE.name });
    const direct = parseMessengerThread(html, { selfName: PAGE.name });

    expect(viaTransport).toEqual(direct);
  });
});

/* -------------------------------------------------- the connection row */

describe('storing which surface a tenant is on', () => {
  let db: Database;
  let t: TestTenant;

  beforeAll(async () => {
    db = await freshDb();
    t = await makeTenant(db, 'fbbiz');
  });

  afterAll(async () => { await db.close(); });

  it('keeps the asset id beside the Page id, not instead of it', async () => {
    await withTenant(db, t.tenantId, (tx) =>
      setFbBridgeConnection({ tx, tenantId: t.tenantId, kek: TEST_KEK }, {
        status: 'ready', pageId: PAGE.id, pageName: PAGE.name, assetId: PAGE.assetId, actorId: null,
      }));

    const stored = await withTenant(db, t.tenantId, (tx) =>
      getFbBridgeConnection({ tx, tenantId: t.tenantId, kek: TEST_KEK }));

    expect(stored.pageId).toBe(PAGE.id);
    expect(stored.assetId).toBe(PAGE.assetId);
    expect(stored.assetId).not.toBe(stored.pageId);
  });

  it('does not blank the asset id on an ordinary status change', async () => {
    // A session expiring must not silently move the tenant back to reading a
    // personal inbox.
    await withTenant(db, t.tenantId, (tx) =>
      setFbBridgeConnection({ tx, tenantId: t.tenantId, kek: TEST_KEK }, {
        status: 'error', lastError: 'sesi habis', actorId: null,
      }));

    const stored = await withTenant(db, t.tenantId, (tx) =>
      getFbBridgeConnection({ tx, tenantId: t.tenantId, kek: TEST_KEK }));

    expect(stored.status).toBe('error');
    expect(stored.assetId).toBe(PAGE.assetId);
  });

  it('clears it when a Page is reconnected as a personal account', async () => {
    await withTenant(db, t.tenantId, (tx) =>
      setFbBridgeConnection({ tx, tenantId: t.tenantId, kek: TEST_KEK }, {
        status: 'ready', pageId: PAGE.id, pageName: PAGE.name, assetId: null, actorId: null,
      }));

    const stored = await withTenant(db, t.tenantId, (tx) =>
      getFbBridgeConnection({ tx, tenantId: t.tenantId, kek: TEST_KEK }));

    expect(stored.assetId).toBeNull();
  });
});

/* ------------------------------------------ Business Suite into the CRM */

describe('a Business Suite conversation reaching the CRM', () => {
  let db: Database;
  let app: FastifyInstance;
  let t: TestTenant;
  let e: Env;

  const post = (body: unknown) => app.inject({
    method: 'POST', url: '/v1/webhooks/fb-bridge',
    headers: { authorization: `Bearer ${e.FB_BRIDGE_SECRET}`, 'content-type': 'application/json' },
    payload: JSON.stringify(body),
  });

  /** Exactly what the watcher emits for a parsed Business Suite transcript. */
  const eventsFromFixture = async () => {
    const parsed = parseBusinessSuiteTranscript(await fixture('business-suite-thread.html'), {
      contactName: CONTACT.name, selfName: PAGE.name,
    });
    return parsed.messages.map((m, seq) => ({
      event: 'message', tenantId: t.tenantId, at: new Date().toISOString(),
      message: {
        threadId: CONTACT.id, externalMessageId: m.externalMessageId,
        senderId: CONTACT.id, senderName: m.senderName, text: m.text,
        sentAt: m.sentAt, direction: m.direction, seq,
      },
    }));
  };

  const storedMessages = () => withTenant(db, t.tenantId, (tx) =>
    tx.query<{ direction: string; sender_type: string; provider_message_id: string }>(
      `select m.direction, m.sender_type, m.provider_message_id
         from messages m join channels ch on ch.id = m.channel_id and ch.tenant_id = m.tenant_id
        where m.tenant_id = $1 and ch.kind = 'messenger_bridge'
        order by m.provider_message_id`,
      [t.tenantId]));

  beforeAll(async () => {
    db = await freshDb();
    t = await makeTenant(db, 'fbbizingest');
    e = env();

    app = buildApp({
      db, control: db, kek: TEST_KEK, env: e,
      dispatch: async ({ queue, payload }) => {
        if (queue !== 'inbound.normalise') return;
        await processInboundWebhook(
          { db, control: db, kek: TEST_KEK, dispatch: async () => {} },
          (payload as { webhookEventId: string }).webhookEventId,
        );
      },
    });
    await app.ready();

    await withTenant(db, t.tenantId, (tx) =>
      ensureMessengerBridgeChannel({ tx, tenantId: t.tenantId, kek: TEST_KEK }, {
        pageId: PAGE.id, pageName: PAGE.name, status: 'connected',
      }));
  });

  afterAll(async () => { await app.close(); await db.close(); });

  it('stores what the customer said as inbound', async () => {
    for (const ev of await eventsFromFixture()) {
      expect((await post(ev)).statusCode).toBe(200);
    }

    const inbound = (await storedMessages()).filter((r) => r.direction === 'inbound');

    expect(inbound).toHaveLength(2);
    expect(inbound.every((r) => r.sender_type === 'contact')).toBe(true);
  });

  it('stores the Page\'s own past reply as outbound history, not as a customer message', async () => {
    const outbound = (await storedMessages()).filter((r) => r.direction === 'outbound');

    expect(outbound).toHaveLength(1);
    expect(outbound[0]!.sender_type).not.toBe('contact');
  });

  it('adds nothing on a second reconciliation of the same thread', async () => {
    const before = (await storedMessages()).length;

    for (const ev of await eventsFromFixture()) {
      expect((await post(ev)).statusCode).toBe(200);
    }

    expect((await storedMessages()).length).toBe(before);
  });

  it('never stores the message the measurement could not read', async () => {
    const rows = await storedMessages();

    expect(rows.some((r) => r.provider_message_id.includes('synthetic0005'))).toBe(false);
  });
});
