/**
 * Every word the user reads, in one file.
 *
 * Two rules were applied to all of it:
 *   1. Bahasa Indonesia, the way a shop supervisor in Jakarta actually talks —
 *      not translated software English.
 *   2. No jargon. "Overage" became "biaya tambahan", "resolve" became "tandai
 *      selesai", "conversation window" became "sudah lewat 24 jam". Where a rule
 *      comes from WhatsApp rather than from us, the copy says so, because a
 *      person who understands *why* stops being afraid of the button.
 *
 * Keeping it in one place means the plain-language pass can be reviewed by
 * someone who does not read React.
 */
export const t = {
  app: {
    name: 'MCNASIA',
    tagline: 'Semua chat client di satu tempat',
  },

  /**
   * Marketing and AI are two divisions of one workspace: same menu, same
   * pages, different data — and different WhatsApp, Instagram, Facebook and
   * Calendar accounts. The switcher in the sidebar picks which one every page
   * shows; the badge on a settings page says whose account is on screen.
   */
  division: {
    label: 'Divisi',
    marketing: 'Marketing',
    ai: 'AI',
    switch: 'Ganti divisi',
    badge: (name: string) => `Divisi: ${name}`,
    hint: 'Data, akun, dan kalender tiap divisi terpisah.',
  },

  search: {
    trigger: 'Cari…',
    shortcut: 'Ctrl+K',
    placeholder: 'Cari client, pesanan, tugas, brand, atau deal…',
    empty: (q: string) => `Tidak ada hasil untuk "${q}".`,
    hint: 'Belum ada yang diketik.',
    categoryLabel: {
      contact: 'Client', order: 'Pesanan', task: 'Tugas', brand: 'Tracker Brand', deal: 'Deal',
    } as Record<string, string>,
  },

  notifications: {
    title: 'Notifikasi',
    empty: 'Tidak ada notifikasi baru.',
    needsReply: 'menunggu balasan',
    taskOverdue: 'lewat jatuh tempo',
    taskDueToday: 'jatuh tempo hari ini',
    commentPending: 'komentar IG perlu dibalas',
    commentFailed: 'balasan komentar IG gagal terkirim',
    botNeedsHelp: 'bot minta bantuan',
    seeAll: 'Lihat semua',
  },

  nav: {
    dashboard: 'Dashboard',
    inbox: 'Inbox',
    chats: 'Obrolan',
    chatWa: 'Chat WA',
    chatIg: 'Chat IG',
    igComments: 'Komentar IG',
    chatFb: 'Chat Facebook',
    fbComments: 'Komentar Facebook',
    client: 'Client',
    clientDeal: 'Client Deal',
    clientProses: 'Client On Proses',
    orders: 'Pesanan',
    tasks: 'Tugas',
    calendar: 'Calendar',
    contact: 'Contact',
    brand: 'Tracker Brand',
    brandManagement: 'Kelola Brand',
    monitoring: 'Monitoring',
    waStatus: 'Status Nomor',
    agentPerformance: 'Performa Agen',
    channelWa: 'Channel WhatsApp',
    sales: 'Deal',
    target: 'Target',
    team: 'Tim',
    customize: 'Customize',
    document: 'Dokumen',
    broadcast: 'Broadcast',
    automation: 'Automation',
    settings: 'Pengaturan',
    signOut: 'Keluar',
    collapse: 'Ciutkan menu',
    expand: 'Perluas menu',
    themeSystem: 'Tampilan: Ikuti Sistem',
    themeLight: 'Tampilan: Terang',
    themeDark: 'Tampilan: Gelap',
  },

  roles: {
    owner: 'Pemilik',
    admin: 'Admin',
    supervisor: 'Supervisor',
    agent: 'Agen',
    viewer: 'Hanya lihat',
  } as Record<string, string>,

  roleNote: {
    owner: 'Bisa semua, termasuk tagihan dan menutup akun',
    admin: 'Bisa semua kecuali tagihan',
    supervisor: 'Bisa buka semua obrolan, bagi tugas, dan lihat nomor lengkap',
    agent: 'Hanya obrolan miliknya atau yang belum dipegang. Nomor client disamarkan',
    viewer: 'Hanya bisa melihat, tidak bisa membalas',
  } as Record<string, string>,

  login: {
    title: 'Masuk ke akun toko Anda',
    subtitle: 'Pakai nama akun yang dibuat oleh admin Anda.',
    shop: 'Nama akun toko',
    shopHint: 'Contoh: toko-demo',
    email: 'Email',
    username: 'Username',
    password: 'Kata sandi',
    submit: 'Masuk',
    demo: 'COBA DULU',
    expired: 'Sesi Anda habis. Silakan masuk lagi.',
    wrong: 'Email atau kata sandi tidak cocok',
    tooMany: 'Terlalu banyak percobaan. Tunggu beberapa menit.',
    offline: 'Tidak bisa menghubungi server',
    incomplete: 'Semua kolom harus diisi',
    stale: 'Halaman ini sudah kedaluwarsa. Muat ulang lalu coba lagi.',
  },

  chats: {
    title: 'Obrolan',
    subtitle: 'Balas client di sini. Yang ada tanda kuning belum dibalas.',
    filterAll: 'Semua',
    filterNeedsReply: 'Perlu dibalas',
    filterDone: 'Selesai',
    needsReply: 'Menunggu balasan Anda',
    nobodyYet: 'Belum dipegang',
    done: 'Selesai',
    emptyList: 'Tidak ada obrolan di sini.',
    pickOne: 'Pilih satu obrolan di kiri',
    pickOneHelp: 'Obrolan paling baru ada di atas. Tanda kuning berarti client sedang menunggu balasan Anda.',
    live: 'Otomatis segarkan',
    paused: 'Berhenti sementara',
    updated: 'Diperbarui',
    refreshing: 'Memuat…',

    takeIt: 'Saya yang tangani',
    handledBy: 'Ditangani oleh',
    assign: 'Simpan',
    markDone: 'Tandai selesai',
    reopen: 'Sudah selesai',
    noOne: 'Belum ada',

    canReplyFreely: 'Bisa balas bebas',
    templateOnly: 'Sudah lewat 24 jam',
    windowClosedTitle: 'Client ini terakhir chat lebih dari 24 jam lalu',
    windowClosedBody:
      'Ini aturan dari WhatsApp, bukan dari kami: kalau sudah lewat 24 jam, balasan harus memakai pesan template yang sudah disetujui Meta. Tulis nama templatenya di bawah, lalu kirim.',
    templateName: 'Nama template',
    templateNameHint: 'contoh: konfirmasi_pesanan',
    writeReply: 'Tulis balasan…',
    writeTemplate: 'Isi pesan template…',
    send: 'Kirim balasan',
    sendTemplate: 'Kirim template',
    sending: 'Mengirim…',
    emptyMessage: 'Tulis pesannya dulu',
    sendFailed: 'Pesan gagal dikirim',
    freeform: 'Masih dalam 24 jam — boleh balas bebas',
    quickReplyButton: 'Balasan Cepat',
    quickReplyEmpty: 'Belum ada balasan cepat. Tambahkan di Pengaturan.',

    /** Keyed by `senderLabelKey` in `lib/chatbot.ts`. */
    sender: {
      contact: 'Client',
      agent: 'Anda / tim',
      autopilot: 'Dijawab otomatis',
      system: 'Sistem',
      bot: 'Bot',
      autopilotApproved: 'Draf AI · disetujui',
      autopilotAuto: 'Autopilot (otomatis)',
    } as Record<string, string>,
    undelivered: 'tidak terkirim',

    redacted: 'sudah dihapus',
    noMessages: 'Belum ada pesan.',

    aboutClient: 'Tentang client',
    name: 'Nama',
    phone: 'Nomor HP',
    lastChat: 'Terakhir chat',
    autoReply: 'Balasan otomatis',
    handling: 'Penanganan',
    status: 'Status',
    ordersHere: 'Pesanan',
    noOrders: 'Belum ada pesanan dari chat ini.',
    orderStatus: {
      draft: 'Sedang disusun', awaiting_payment: 'Menunggu bayar',
      paid: 'Sudah dibayar', cancelled: 'Dibatalkan', fulfilled: 'Sudah dikirim',
    } as Record<string, string>,
    salesHere: 'Deal',
    noSales: 'Belum ada deal untuk client ini.',
    inProgress: 'dalam proses',
    billingNote:
      'Satu client dihitung 1 obrolan per 24 jam, berapa pun jumlah pesannya.',
    addClientTitle: 'Tambah sebagai Client',
    addClientHint: 'Client ini akan langsung masuk ke Client On Proses. Jadwal meeting opsional — bisa diisi sekarang atau menyusul nanti.',
    addClientSaving: 'Menyimpan…',
    addClientFailed: 'Gagal menambahkan sebagai client',
    alreadyClient: 'Sudah jadi client',
  },

  autopilot: {
    ready: 'Balasan otomatis sudah disiapkan',
    confidence: 'yakin',
    explain: 'Ini belum terkirim. Baca dulu, baru putuskan.',
    use: 'Pakai & kirim',
    edit: 'Ubah dulu',
    sendEdited: 'Kirim yang sudah diubah',
    cancelEdit: 'Batal',
    discard: 'Abaikan',
    working: 'Sebentar…',
    failed: 'Gagal memproses balasan otomatis',

    title: 'Balasan otomatis',
    subtitle: 'Seberapa jauh robot boleh menjawab sendiri, dan dari katalog mana dia menjawab.',
    mode: 'Cara kerja',
    modeOff: 'Mati',
    modeOffNote: 'Tidak menyiapkan apa pun.',
    modeSuggest: 'Siapkan draf saja',
    modeSuggestNote: 'Robot menulis, orang yang menekan kirim. Mulai dari sini.',
    modeAuto: 'Balas sendiri',
    modeAutoNote: 'Robot langsung membalas, tapi hanya kalau semua pemeriksaan lolos.',
    save: 'Simpan',
    saved: 'Tersimpan.',
    guardTitle: 'Yang selalu diperiksa sebelum terkirim',
    guards: [
      'Harga harus ada di katalog. Angka karangan langsung ditahan.',
      'Tidak boleh menjanjikan diskon atau tanggal barang pasti sampai.',
      'Tidak boleh bilang stok ada kalau di katalog stoknya nol.',
      'Client yang komplain selalu diserahkan ke orang.',
      'Kalau robot ragu, orang yang menjawab.',
    ],
    capTitle: 'Batas aman',
    capBody: (n: number) =>
      `Maksimal ${n} balasan otomatis per jam untuk seluruh toko. Kalau chat membanjir, robot berhenti dan orang yang lanjut — supaya biaya tidak lari.`,
    capOff: 'Tidak ada batas jumlah balasan otomatis per jam.',
    stats: 'Sebulan terakhir',
    statPending: 'Menunggu diperiksa',
    statUsed: 'Dipakai apa adanya',
    statEdited: 'Dipakai setelah diubah',
    statAuto: 'Dikirim sendiri',
    statBlocked: 'Ditahan pemeriksaan',
    statDiscarded: 'Dibuang',
    catalogue: 'Katalog & aturan',
    catalogueNote: 'Robot hanya boleh menjawab dari daftar ini. Kalau tidak ada di sini, dia menyerahkan ke orang.',
    kind: 'Jenis',
    itemTitle: 'Nama',
    sku: 'Kode',
    price: 'Harga',
    stock: 'Stok',
    emptyCatalogue: 'Katalog masih kosong. Selama kosong, robot tidak akan menjawab sendiri.',
    kinds: { product: 'Produk', faq: 'Tanya jawab', policy: 'Aturan' } as Record<string, string>,
  },

  /** Why a draft was held back, in words a supervisor can act on. */
  guardReasons: {
    ungrounded_price: 'Harga tidak ada di katalog',
    discount_not_allowed: 'Menjanjikan diskon',
    delivery_promise_not_allowed: 'Menjanjikan tanggal sampai',
    unknown_sku: 'Menyebut produk yang tidak ada',
    out_of_stock_claim: 'Bilang ada padahal stok habis',
    too_long: 'Balasan kepanjangan',
    empty_reply: 'Balasan kosong',
    external_link: 'Ada tautan asing',
    escalation_keyword: 'Client sedang komplain',
    low_confidence: 'Robot kurang yakin',
    model_asked_for_human: 'Robot minta dibantu orang',
    model_refused: 'Robot menolak menjawab',
    mode_off: 'Balasan otomatis sedang mati',
    mode_suggest: 'Mode siapkan draf',
  } as Record<string, string>,

  /**
   * The trained-cb bot that answers WhatsApp Web, Instagram and Messenger DMs
   * until a person takes the conversation over. Not Autopilot: Autopilot
   * writes drafts for the Meta channels and keeps its own page.
   */
  chatbot: {
    title: 'Chatbot',
    subtitle: 'Bot yang membalas DM WhatsApp, Instagram, dan Facebook Messenger sendiri — sampai ada orang yang mengambil alih.',
    switchTitle: 'Chatbot (trained-cb)',
    on: 'Aktif',
    onNote: 'Bot membalas DM di akun yang chatbot-nya dinyalakan di bawah.',
    off: 'Nonaktif',
    offNote: 'Bot tidak membalas apa pun di divisi ini. Semua DM dijawab orang.',
    save: 'Simpan',
    saving: 'Menyimpan…',
    saved: 'Tersimpan.',
    failed: 'Gagal menyimpan pengaturan chatbot',

    brainMissingTitle: 'Bot belum tersambung ke layanannya',
    brainMissing: 'Dalam 24 jam terakhir ada pesan yang dilewati bot karena layanan trained-cb belum diatur di server. Selama itu bot tidak membalas apa pun — hubungi admin teknis.',

    countsTitle: 'Obrolan yang masih berjalan',
    handling: {
      bot: 'Bot aktif', human: 'Ditangani manusia', needs_human: 'Perlu bantuan',
    } as Record<string, string>,

    channelsTitle: 'Akun DM',
    channelsNote: 'Bot hanya membalas di akun yang dinyalakan di sini. Akun yang baru disambungkan mulai dalam keadaan mati.',
    divisionOffNote: 'Chatbot divisi ini sedang nonaktif, jadi akun yang menyala pun belum dibalas bot.',
    noChannels: 'Belum ada akun WhatsApp Web, Instagram, atau Facebook di divisi ini.',
    channelName: 'Akun',
    channelKind: 'Jenis',
    channelStatus: 'Koneksi',
    channelChatbot: 'Chatbot aktif',
    channelOn: 'Nyala',
    channelOff: 'Mati',
    turnOn: 'Nyalakan',
    turnOff: 'Matikan',
    channelFailed: 'Gagal mengubah chatbot akun ini',
    messengerNote: 'Nyalakan hanya setelah uji kirim langsung ke Messenger berhasil.',
    channelStatuses: {
      connecting: 'Menyambung', connected: 'Tersambung', error: 'Bermasalah', disabled: 'Terputus',
    } as Record<string, string>,

    takeover: 'Ambil alih',
    resume: 'Aktifkan bot kembali',
    working: 'Sebentar…',
    takeoverFailed: 'Gagal mengambil alih dari bot',
    resumeFailed: 'Gagal mengaktifkan bot kembali',
    optOut: 'Minta bot berhenti',
    optOutHint: 'Kontak ini minta tidak dibalas bot lagi, jadi bot tidak bisa diaktifkan kembali. Orang yang melanjutkan.',
    /** Reasons the CRM itself records; anything else is trained-cb's own words, shown as they are. */
    reasons: {
      verify_booking: 'cek jadwal meeting, booking belum pasti tercatat',
      booked_during_takeover: 'bot sudah menjadwalkan meeting, konfirmasinya belum dikirim ke kontak',
    } as Record<string, string>,

    inboxBot: 'Bot',
    inboxNeedsHelp: 'Perlu bantuan',
  },

  catalogue: {
    title: 'Katalog',
    subtitle: 'Robot hanya boleh menjawab dari daftar ini. Isi yang rapi di sini = jawaban yang benar di chat.',
    products: 'Produk',
    productsNote: 'Harga dan stok di sini yang dipakai robot untuk menjawab dan membuat pesanan.',
    name: 'Nama barang',
    sku: 'Kode',
    skuHint: 'contoh: KML-01',
    price: 'Harga',
    stock: 'Stok',
    note: 'Catatan',
    noteHint: 'warna, bahan, ukuran…',
    save: 'Simpan',
    saving: 'Menyimpan…',
    remove: 'Hapus',
    add: 'Tambah produk',
    addNote: 'Tambah tanya jawab / aturan',
    emptyProducts: 'Belum ada produk. Selama kosong, robot menyerahkan semua chat ke orang.',
    notes: 'Tanya jawab & aturan',
    notesNote: 'Hal yang sering ditanya: retur, cara bayar, jam kirim. Robot memakai ini apa adanya.',
    noteTitle: 'Judul',
    noteBody: 'Isi',
    kind: 'Jenis',
    kindFaq: 'Tanya jawab',
    kindPolicy: 'Aturan',
    emptyNotes: 'Belum ada catatan.',
    shipping: 'Ongkir',
    shippingNote: 'Tanpa ini robot tidak bisa menghitung total pesanan. Pakai "default" untuk daerah lain.',
    area: 'Daerah',
    cost: 'Biaya',
    eta: 'Estimasi hari',
    emptyShipping: 'Belum ada ongkir. Robot tidak akan bisa mengunci pesanan.',
    failed: 'Gagal menyimpan',
    saved: 'Tersimpan.',
  },

  security: {
    title: 'Keamanan',
    subtitle: 'Lapisan kedua supaya kata sandi saja tidak cukup untuk masuk.',
    twoStep: 'Verifikasi dua langkah',
    offNow: 'Belum aktif',
    onNow: 'Aktif',
    why: 'Kalau kata sandi Anda bocor, orang itu tetap tidak bisa masuk tanpa HP Anda. Sangat dianjurkan untuk Pemilik dan Admin.',
    turnOn: 'Nyalakan',
    step1: 'Buka aplikasi Google Authenticator atau Authy, pilih tambah akun, lalu masukkan kode di bawah ini.',
    secretLabel: 'Kunci untuk aplikasi',
    orOpen: 'Atau buka tautan ini di HP',
    step2: 'Masukkan 6 angka yang muncul di aplikasi',
    codeLabel: 'Kode 6 angka',
    confirm: 'Aktifkan',
    working: 'Sebentar…',
    cancel: 'Batal',
    turnOff: 'Matikan',
    turnOffHint: 'Masukkan kode dari aplikasi untuk mematikan',
    backupTitle: 'Kode cadangan',
    backupNote: 'Simpan sekarang. Kode ini hanya muncul sekali, dan dipakai kalau HP Anda hilang. Satu kode sekali pakai.',
    backupLeft: (n: number) => `${n} kode cadangan tersisa`,
    codeWrong: 'Kode tidak cocok. Cek jam di HP Anda, lalu coba lagi.',
    failed: 'Gagal memproses',

    eventsTitle: 'Kejadian keamanan',
    eventsNote: 'Hal-hal yang perlu dilihat orang. Yang bertanda merah punya batas waktu lapor.',
    eventsEmpty: 'Belum ada kejadian. Ini kabar baik.',
    clocksRunning: (n: number) => `${n} perlu dilaporkan`,
    kinds: {
      audit_chain_broken: 'Catatan riwayat diubah dari luar aplikasi',
      cross_tenant_denied: 'Ada yang mencoba membuka data toko lain',
      refresh_token_reuse: 'Token sesi dipakai dua kali — kemungkinan disalin',
      login_lockout: 'Terlalu banyak percobaan masuk yang salah',
      mfa_lockout: 'Terlalu banyak kode dua langkah yang salah',
      webhook_signature_flood: 'Banyak kiriman webhook tanpa tanda tangan sah',
      bulk_contact_reveal: 'Banyak nomor client dibuka oleh satu orang',
      dsr_overdue: 'Permintaan data client lewat batas waktu',
    } as Record<string, string>,
    clock: {
      not_applicable: 'Tidak perlu lapor',
      running: 'Batas lapor berjalan',
      due_soon: 'Kurang dari 12 jam',
      overdue: 'LEWAT BATAS',
      notified: 'Sudah dilaporkan',
    } as Record<string, string>,
    ack: 'Tandai sudah dibaca',
    reported: 'Catat sudah dilaporkan',
    reportedHint: 'Tulis siapa yang sudah diberi tahu dan kapan',
    deadline: 'Batas lapor',

    signInTitle: 'Masukkan kode dari aplikasi',
    signInHelp: 'Buka aplikasi authenticator Anda dan ketik 6 angka yang muncul. Kalau HP Anda hilang, pakai salah satu kode cadangan.',
    signInSubmit: 'Lanjut',
    signInExpired: 'Waktunya habis. Masuk lagi dari awal.',
  },

  sales: {
    title: 'Deal',
    subtitle: 'Geser deal ke tahap berikutnya. Yang ada tanda oranye sudah lama tidak ada kabar.',
    inProgress: 'dalam proses',
    won: 'berhasil',
    quiet: 'lama diam',
    quietChip: 'Lama diam',
    wonChip: 'Berhasil',
    lostChip: 'Batal',
    moveTo: 'Pindahkan ke',
    empty: 'Kosong',
    moveFailed: 'Gagal memindahkan',
    autoNote: 'Tahap pindah sendiri kalau client sudah bayar atau membuka penawaran.',
    noneYet: 'Belum ada deal',
    noneYetHelp: 'Klik "Tambah deal" untuk membuat deal baru dari sebuah brand.',
    add: 'Tambah deal',
    addTitle: (stage: string) => `Deal Baru — ${stage}`,
    addFailed: 'Gagal menambah deal',
    discard: 'Batal',
    edit: 'Edit',
    editTitle: (name: string) => `Edit Deal — ${name}`,
    editFailed: 'Gagal menyimpan perubahan deal',
    delete: 'Hapus',
    deleteTitle: 'Hapus deal ini?',
    deleteWarning: (name: string) =>
      `"${name}" akan dihapus permanen. Tugas dan pesanan yang terhubung tetap tersimpan, tapi tautannya ke deal ini akan hilang.`,
    deleteConfirm: 'Ya, hapus',
    hasMeeting: 'Ada tugas Meeting terjadwal',
    hasCall: 'Ada tugas Telepon terjadwal',
    hasOnlineMeet: 'Ada tugas Online Meet terjadwal',
    actionChat: 'Buka chat WhatsApp',
    actionNoChat: 'Belum ada percakapan',
    actionDetail: 'Lihat detail',
    detail: 'Detail',
    table: {
      brand: 'Brand',
      category: 'Kategori',
      stage: 'Status',
      amount: 'Nilai',
      status: 'Kondisi',
      action: 'Aksi',
    },
  },

  target: {
    title: 'Target Penjualan',
    subtitle: 'Pasang target per periode, untuk seluruh tim atau per agen — pencapaiannya dihitung otomatis dari penjualan yang berhasil (won), jadi selalu sesuai data terbaru.',
    wholeTeam: 'Seluruh Tim',
    achieved: 'Tercapai',
    ofTarget: 'dari target',
    remaining: 'Kurang',
    statusDone: 'Tercapai',
    statusBehind: 'Belum tercapai',
    period: 'Periode',
    periodStart: 'Mulai',
    periodEnd: 'Sampai',
    owner: 'Untuk',
    amount: 'Nilai Target',
    notes: 'Catatan',
    notesPlaceholder: 'Opsional',
    add: 'Tambah Target',
    save: 'Simpan',
    saving: 'Menyimpan…',
    remove: 'Hapus',
    empty: 'Belum ada target. Tambahkan target penjualan pertama di bawah.',
    failed: 'Gagal menyimpan target',
    manage: 'Kelola Target',
  },

  dealDetail: {
    back: 'Deal',
    summary: 'Ringkasan',
    amount: 'Nilai',
    stage: 'Tahap',
    contact: 'Client',
    owner: 'Pemilik',
    noOwner: 'Belum ada',
    created: 'Dibuat',
    brand: 'Brand',
    chooseBrand: 'Pilih brand…',
    noBrand: 'Belum dipilih',
    category: 'Kategori',
    noCategory: '—',
    expectedClose: 'Target Penutupan',
    noExpectedClose: 'Belum ditentukan',
    notes: 'Catatan',
    notesPlaceholder: 'Tulis catatan soal deal ini — apa yang client bilang, kenapa macet, apa langkah berikutnya…',
    save: 'Simpan',
    saving: 'Menyimpan…',
    saved: 'Tersimpan.',
    failed: 'Gagal menyimpan',
    relatedOrders: 'Pesanan Terkait',
    noOrders: 'Belum ada pesanan dari deal ini.',
    stageFlow: 'Alur Tahap',
    openChip: 'Berjalan',
    lostReason: 'Alasan batal',
    notFound: 'Deal ini tidak ditemukan — mungkin sudah dihapus.',
  },

  team: {
    title: 'Tim',
    subtitle: 'Siapa saja yang bisa masuk, dan apa yang boleh mereka lakukan.',
    people: 'orang',
    person: 'Orang',
    role: 'Peran',
    whatTheyCanDo: 'Boleh melakukan apa',
    lastSeen: 'Terakhir masuk',
    you: 'Anda',
    add: 'Tambah orang',
    addName: 'Nama',
    addEmail: 'Email',
    addRole: 'Peran',
    addPassword: 'Kata sandi sementara',
    addPasswordHint: 'minimal 12 huruf',
    addSubmit: 'Tambahkan',
    adding: 'Menambahkan…',
    added: 'Sudah ditambahkan. Minta dia ganti kata sandi setelah masuk pertama kali.',
    passwordShort: 'Kata sandi sementara minimal 12 huruf',
    addFailed: 'Gagal menambahkan orang',
    onlyAdmin: 'Hanya Pemilik atau Admin yang bisa menambah orang.',
    auditNote: 'Setiap penambahan tercatat di Riwayat.',
  },

  settings: {
    title: 'Pengaturan',
    tabBill: 'Tagihan',
    tabEmail: 'Email',
    tabInstagram: 'Instagram',
    tabFacebook: 'Facebook',
    tabHistory: 'Riwayat',

    usageTitle: 'Pemakaian bulan ini',
    usageSubtitle: 'Yang Anda bayar adalah jumlah obrolan, bukan jumlah pesan.',
    plan: 'Paket',
    chats: 'Obrolan',
    ofIncluded: 'dari',
    included: 'yang termasuk paket',
    autoReplies: 'Balasan otomatis',
    extra: 'Biaya tambahan',
    insidePlan: 'Masih di dalam paket',
    beyondPlan: 'lebih dari jatah paket',
    estimate: 'Perkiraan tagihan',
    exVat: 'belum termasuk PPN',
    thisMonth: 'Rincian bulan ini',
    line: 'Keterangan',
    qty: 'Jumlah',
    amount: 'Nilai',
    planLine: 'Paket',
    extraLine: 'Obrolan lebih dari jatah',
    metaLine: 'Biaya WhatsApp',
    metaNote: 'Ditagih Meta, kami teruskan apa adanya tanpa tambahan',
    plans: 'Pilihan paket',
    plansNote: 'Makin banyak obrolan, makin murah harga per obrolannya.',
    current: 'Paket Anda',
    suggested: 'Lebih hemat',
    perMonth: 'Per bulan',
    perChat: 'Per obrolan',
    numbers: 'Nomor WA',
    seats: 'Akun tim',
    extraPerChat: 'Kelebihan per obrolan',
    upgradeTitle: 'Bisa lebih hemat',
    upgradeBody: (plan: string, over: string) =>
      `Pemakaian Anda sudah lewat jatah paket. Naik ke paket ${plan} lebih murah daripada bayar kelebihan ${over}. Kami naikkan otomatis, bukan menagih selisihnya.`,
    countedHow: 'Cara hitungnya',
    countedHowBody:
      'Satu client yang chat dihitung 1 obrolan untuk 24 jam ke depan — mau dia kirim 2 pesan atau 50 pesan, tetap 1. Kalau dia chat lagi tiga hari kemudian, baru dihitung lagi.',

    invoices: 'Tagihan dari MCNASIA',
    invoicesNote: 'Ini tagihan toko Anda ke MCNASIA. Pembayaran lewat transfer bank.',
    invoicesEmpty: 'Belum ada tagihan. Tagihan pertama terbit di akhir periode.',
    invNumber: 'Nomor',
    invIssued: 'Terbit',
    invDue: 'Jatuh tempo',
    invTotal: 'Total',
    invStatus: 'Status',
    invOutstanding: 'Belum dibayar',
    invStatuses: {
      draft: 'Draf', issued: 'Menunggu bayar', paid: 'Lunas',
      overdue: 'Lewat jatuh tempo', void: 'Dibatalkan', written_off: 'Dihapusbukukan',
    } as Record<string, string>,
    markPaid: 'Tandai lunas',
    markPaidHint: 'Nomor referensi transfer',
    invFailed: 'Gagal menyimpan pembayaran',
    invPpn: 'termasuk PPN',

    historyTitle: 'Riwayat',
    historySubtitle: 'Catatan semua yang pernah terjadi. Tidak bisa diubah atau dihapus oleh siapa pun.',
    intact: 'Catatan utuh',
    broken: 'Catatan pernah diubah',
    what: 'Kegiatan',
    who: 'Oleh',
    detail: 'Rincian',
    when: 'Kapan',
    noHistory: 'Belum ada catatan.',
  },

  emailSettings: {
    title: 'Email',
    subtitle: 'Atur SMTP sendiri supaya email (undangan meeting, dan lainnya nanti) terkirim dari alamat Anda sendiri — kalau tidak diisi, sistem pakai pengaturan bawaan.',
    smtpUrl: 'SMTP URL',
    smtpUrlPlaceholder: 'smtps://user:password@smtp.penyedia.com:465',
    smtpUrlHint: 'Format koneksi SMTP standar — didukung Gmail, SendGrid, Mailgun, dan sebagian besar penyedia email lain.',
    smtpUrlConfigured: 'Sudah diisi — kosongkan kolom ini kalau tidak mau menggantinya.',
    smtpUrlNotConfigured: 'Belum diisi — email dikirim lewat pengaturan bawaan sistem.',
    emailFrom: 'Nama & Alamat Pengirim',
    emailFromPlaceholder: 'Nama Toko <halo@tokoanda.com>',
    save: 'Simpan',
    saving: 'Menyimpan…',
    saved: 'Tersimpan.',
    failed: 'Gagal menyimpan pengaturan email',
    lastUpdated: (when: string) => `Terakhir diubah ${when}`,
  },

  facebookBridge: {
    title: 'Facebook',
    sectionTitle: 'Facebook Messenger & Komentar (Tidak Resmi)',
    subtitle: 'Facebook dibaca lewat browser otomatis yang login sebagai akun operator, bukan lewat API resmi Meta. Cara ini melanggar Ketentuan Layanan Facebook dan berisiko akun kena checkpoint. Balasan DM dikirim dari Obrolan.',
    inboundOnly: 'Pesan masuk dan balasan sudah jalan, termasuk balasan publik ke komentar. Chatbot untuk Messenger dinyalakan per Halaman di Pengaturan → Chatbot, setelah uji kirim langsung berhasil. Pemindahan ke WhatsApp belum tersedia untuk Facebook.',
    pageId: 'ID Halaman',
    pageIdPlaceholder: 'mis. 61594393176093',
    pageIdHint: 'Angka di URL Halaman Anda. Buka Halaman di Facebook, lihat bagian profile.php?id=… atau Pengaturan Halaman.',
    pageName: 'Nama Halaman',
    pageNamePlaceholder: 'mis. Red Panda Test',
    pageNameHint: 'Harus persis sama dengan yang Facebook tampilkan. Nama ini yang dipakai untuk membedakan balasan Anda sendiri dari pesan pelanggan.',
    assetId: 'ID aset Business Suite',
    assetIdPlaceholder: 'mis. 1225922357281590',
    /** The one hint on this form that has to say "not that number": the two
     * ids look alike, the wrong one produces a Business Suite page that loads
     * fine and holds nobody's conversations, and nothing errors. */
    assetIdHint: 'Angka asset_id di URL business.facebook.com/latest/inbox/…?asset_id=… — ini BUKAN ID Halaman. Isi untuk Halaman yang inbox-nya ada di Business Suite; kosongkan kalau yang dibaca inbox pribadi.',
    assetIdInvalid: 'Asset ID harus berupa angka saja, minimal 6 digit. Salin persis dari asset_id= di URL Business Suite.',
    surfaceBusinessSuite: (assetId: string) => `Pesan dibaca dari Meta Business Suite (asset ${assetId}).`,
    surfaceMessenger: 'Pesan dibaca dari Messenger biasa (akun pribadi). Kalau ini sebenarnya Halaman bisnis, putuskan lalu hubungkan ulang sambil mengisi Asset ID — kalau tidak, pesan pelanggan tidak akan terbaca sama sekali.',
    connect: 'Hubungkan Halaman',
    connecting: 'Membuka jendela login…',
    disconnect: 'Putuskan',
    disconnecting: 'Memutuskan…',
    connectedAs: (page: string) => `Terhubung sebagai ${page}`,
    awaitingTitle: 'Menunggu login manual',
    awaitingBody: 'Jendela browser sudah dibuka di mesin yang menjalankan fb-bridge. Selesaikan login Facebook di sana, termasuk 2FA atau checkpoint kalau diminta. Halaman ini akan memperbarui sendiri.',
    checkpointTitle: 'Facebook minta verifikasi',
    checkpointBody: 'Facebook menahan sesi dan menunggu orang. Buka jendela login lagi lewat tombol di bawah, lalu selesaikan verifikasinya secara manual.',
    noCredentialNote: 'CRM tidak pernah menerima atau menyimpan password Facebook Anda. Login dilakukan sendiri di jendela browser, dan yang tersimpan hanya sesi di disk layanan bridge.',
    bridgeUnreachable: 'Layanan Facebook Bridge tidak bisa dihubungi. Pastikan sudah dijalankan (npm run dev:fb-bridge).',
    missingFields: 'Isi ID dan nama Halaman Facebook',
    failed: 'Gagal menghubungkan Facebook',
    lastUpdated: (at: string) => `Diperbarui ${at}`,
    statusLabel: 'Status',
    statusReady: 'Aktif',
    statusAwaiting: 'Menunggu login',
    statusCheckpoint: 'Perlu verifikasi',
    statusError: 'Bermasalah',
    statusDisconnected: 'Belum terhubung',
    commentsTitle: 'Komentar Masuk',
    commentsEmpty: 'Belum ada komentar yang masuk.',
    commentsHint: 'Komentar ditarik berkala dari post Halaman. Tidak ada balasan otomatis.',
    commentOnPost: (postId: string) => `Post ${postId}`,
  },

  instagramBridge: {
    title: 'Instagram',
    sectionTitle: 'Login Otomatis (Tidak Resmi)',
    subtitle: 'Login Instagram lewat browser otomatis di server (bukan API resmi buat developer) — cara ini tetap melanggar Ketentuan Layanan Instagram dan berisiko akun kena checkpoint atau terkunci. Pakai akun cadangan dulu kalau belum yakin.',
    methodLabel: 'Metode Login',
    methodBrowser: 'Login lewat Browser (paling mudah)',
    methodPassword: 'Username & Password',
    methodCookie: 'Session Cookie',
    loginWithBrowser: 'Buka Halaman Login Instagram',
    openingWindow: 'Membuka jendela login…',
    browserHint: 'Cara paling gampang dan paling aman: klik tombol di bawah, lalu jendela Instagram akan terbuka di komputer yang menjalankan ig-bridge. Login sendiri di sana seperti biasa — termasuk kode 2FA atau verifikasi kalau diminta. Sessionid, csrftoken, dan ds_user_id akan terambil otomatis, jadi Anda tidak perlu menyalinnya sendiri dari DevTools. Password Instagram Anda tidak pernah masuk ke CRM ini.',
    awaitingTitle: 'Menunggu login manual',
    awaitingBody: 'Jendela Instagram sudah terbuka di komputer yang menjalankan ig-bridge. Selesaikan login di sana — halaman ini akan memperbarui sendiri begitu berhasil. Jendelanya menunggu sampai 15 menit.',
    bridgeUnreachable: 'Layanan Instagram Bridge tidak bisa dihubungi — pastikan sudah dijalankan (npm run dev:ig-bridge).',
    capturedTitle: 'Diambil otomatis dari login tadi',
    usernameMissing: 'Sesi aktif, tapi username Instagram belum terbaca. Halaman ini sedang mencoba membacanya ulang — kalau tetap kosong, Putuskan lalu login lagi.',
    username: 'Username Instagram',
    usernamePlaceholder: 'namaakun',
    password: 'Password',
    connect: 'Hubungkan',
    connecting: 'Menghubungkan…',
    missingFields: 'Isi username dan password',
    cookieHint: 'Ambil sessionid dari browser yang sudah login ke Instagram, bukan dari akun orang lain.',
    cookieGuideTitle: 'Cara ambil session cookie',
    cookieGuideSteps: [
      'Buka instagram.com di browser dan pastikan sudah login.',
      'Tekan F12 (DevTools) → tab Application (Chrome) atau Storage (Firefox).',
      'Buka Cookies → https://www.instagram.com.',
      'Salin nilai sessionid (wajib). csrftoken dan ds_user_id opsional tapi disarankan.',
    ],
    sessionId: 'sessionid',
    sessionIdPlaceholder: 'Tempel nilai cookie sessionid',
    csrfToken: 'csrftoken (opsional)',
    dsUserId: 'ds_user_id (opsional)',
    missingCookieFields: 'Isi username dan sessionid',
    connectedAs: (username: string) => `Terhubung sebagai @${username}`,
    disconnect: 'Putuskan',
    disconnecting: 'Memutuskan…',
    challengeTitle: 'Perlu verifikasi tambahan',
    challengeHintTwoFactor: 'Instagram minta kode autentikasi dua langkah — cek aplikasi authenticator atau SMS Anda.',
    challengeHintCheckpoint: 'Instagram menandai login ini sebagai mencurigakan dan minta kode verifikasi — cek email atau SMS yang terdaftar di akun tersebut.',
    challengeHintUnknown: 'Instagram minta langkah verifikasi tambahan sebelum login bisa lanjut.',
    code: 'Kode Verifikasi',
    codePlaceholder: '123456',
    submitCode: 'Kirim Kode',
    submittingCode: 'Mengirim…',
    missingCode: 'Isi kode verifikasi',
    failed: 'Gagal menghubungkan Instagram',
    lastUpdated: (when: string) => `Terakhir diubah ${when}`,
  },

  instagramMeta: {
    sectionTitle: 'API Resmi (Meta)',
    subtitle: 'Jalur resmi Instagram Graph API — tidak melanggar Ketentuan Layanan. Generate token dari Meta App Dashboard (Instagram > API setup with Instagram Login > Generate access tokens), lalu tempel di sini. Token berlaku ~60 hari, setelah itu generate ulang.',
    accessToken: 'Access Token',
    accessTokenPlaceholder: 'IGAA…',
    connect: 'Verifikasi & Simpan',
    connecting: 'Memverifikasi…',
    missingToken: 'Tempel access token-nya dulu',
    connectedAs: (username: string) => `Terhubung sebagai @${username}`,
    disconnect: 'Putuskan',
    disconnecting: 'Memutuskan…',
    failed: 'Gagal memverifikasi token Instagram',
    lastUpdated: (when: string) => `Terakhir diubah ${when}`,
  },

  /** Machine event names, said in words. The raw name stays visible underneath. */
  events: {
    'auth.login': 'Masuk ke akun',
    'auth.logout': 'Keluar dari akun',
    'auth.refresh_reuse_detected': 'Sesi mencurigakan diblokir',
    'message.sent': 'Kirim pesan',
    'conversation.assigned': 'Obrolan dibagi ke orang',
    'conversation.resolved': 'Obrolan ditandai selesai',
    'conversation.started': 'Percakapan dimulai',
    'contact.created': 'Client ditambahkan',
    'contact.updated': 'Data client diperbarui',
    'deal.created': 'Deal dibuat',
    'deal.moved': 'Deal pindah tahap',
    'deal.updated': 'Detail deal diperbarui',
    'order.confirmed': 'Pesanan dikunci, menunggu bayar',
    'order.paid_manually': 'Pesanan ditandai dibayar',
    'order.fulfilled': 'Pesanan ditandai terkirim',
    'order.released': 'Pesanan dibatalkan',
    'task.created': 'Tugas dibuat',
    'task.completed': 'Tugas ditandai selesai',
    'task.cancelled': 'Tugas dihapus',
    'member.invited': 'Anggota tim ditambah',
    'user.created': 'Anggota tim dibuat',
    'channel.connected': 'Saluran chat disambungkan',
    'channel.disconnected': 'Saluran chat diputus',
    'tenant.provisioned': 'Akun toko dibuat',
    'billing.period_closed': 'Periode tagihan ditutup',
    'retention.purged': 'Data lama dihapus otomatis',
    'dsr.erasure.completed': 'Data client dihapus atas permintaan',
  } as Record<string, string>,

  /** Keys that show up in history details, said in words. */
  metaKeys: {
    role: 'peran', plan: 'paket', kind: 'jenis', slug: 'nama akun',
    assigneeId: 'ditugaskan ke', stageId: 'tahap', status: 'status',
    amountIdr: 'nilai', messageId: 'pesan', template: 'template',
    messagesRedacted: 'pesan dihapus', conversations: 'obrolan',
    subtotalIdr: 'subtotal', retentionDays: 'simpan (hari)',
    timelineDeleted: 'riwayat dihapus', outcome: 'hasil',
  } as Record<string, string>,

  actors: {
    user: 'Orang',
    api_key: 'Aplikasi lain',
    system: 'Sistem',
    support: 'Tim MCNASIA',
  } as Record<string, string>,

  channels: {
    whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger',
    messenger_bridge: 'Facebook',
    tiktok: 'TikTok', telegram: 'Telegram', tokopedia: 'Tokopedia',
    shopee: 'Shopee', email: 'Email', webchat: 'Chat web', whatsapp_web: 'WhatsApp (manual)',
    instagram_bridge: 'Instagram (tidak resmi)',
  } as Record<string, string>,

  statuses: {
    open: 'Berjalan', pending: 'Menunggu', snoozed: 'Ditunda', resolved: 'Selesai',
  } as Record<string, string>,

  igComments: {
    title: 'Komentar IG',
    subtitle: 'Komentar di postingan Instagram Anda. Balasan publik dibuat singkat — penjelasan lengkapnya lewat DM.',
    tabAll: 'Semua',
    tabPending: 'Perlu dibalas',
    empty: 'Belum ada komentar masuk.',
    onPost: 'di postingan',
    commentCount: 'komentar',
    draftLabel: 'Draft balasan publik',
    copy: 'Salin',
    copied: 'Tersalin',
    markSent: 'Tandai sudah dibalas',
    skip: 'Lewati',
    statusPublicSent: 'Sudah dibalas publik',
    statusPublicPending: 'Belum dibalas',
    statusPublicSkipped: 'Dilewati',
    statusPublicFailed: 'Balasan publik gagal',
    statusDmSent: 'DM terkirim',
    statusDmFailed: 'DM gagal',
    openInstagram: 'Buka di Instagram',
    // Sengaja pendek dan tanpa harga/paket/nama: komentar dibaca semua orang
    // yang lewat, jadi penjelasan lengkapnya ditaruh di DM. Teks ini kembaran
    // REPLY_KOMENTAR_PUBLIK di trained-cb — kalau nanti endpoint komentar di
    // sana sudah ada, draft-nya diambil dari situ, bukan dari sini.
    draftPublicReply: 'Halo Kak, terima kasih sudah mampir 🙏 Info lengkapnya sudah kami kirim lewat DM ya',
  },

  /** The unified inbox: one list for DMs and public comments across platforms. */
  inbox: {
    channelAll: 'Semua kanal',
    channelWhatsapp: 'WhatsApp',
    channelFacebookDm: 'Facebook DM',
    channelInstagramDm: 'Instagram DM',
    channelFacebookComment: 'Komentar Facebook',
    channelInstagramComment: 'Komentar Instagram',
    /** Said in the list itself, not hidden in a tooltip: a filter that is empty
     * because the feature has not landed reads exactly like one that is empty
     * because nobody commented, and an agent would sit waiting for messages
     * that were never going to arrive. */
    instagramCommentsNotReady: 'Komentar Instagram belum terhubung di versi ini.',
    /**
     * Shown only when the request actually failed — never when it succeeded
     * and the answer was genuinely an empty list.
     *
     * Without this the two are indistinguishable, and the wrong one is the
     * dangerous one: an agent reads an empty list as "nobody commented" and
     * stops looking, while real customers sit unanswered behind a broken
     * endpoint. Confirmed live during review — 67 failed requests produced a
     * calm, empty, entirely convincing inbox.
     */
    commentsUnavailable: 'Komentar Facebook sementara tidak dapat dimuat.',

    commentBadge: 'Komentar',
    commentOn: 'Komentar di postingan',
    commenter: 'Pengomentar',
    commentBody: 'Isi komentar',
    postContext: 'Postingan',
    openOnFacebook: 'Buka di Facebook',
    pickOne: 'Pilih satu item di kiri',
    pickOneHelp: 'DM dan komentar tampil bersama, yang paling baru di atas.',

    replyPublic: 'Balas publik',
    sendDm: 'Kirim DM',
    replyPublicLabel: 'Balasan publik di postingan',
    dmLabel: 'Pesan pribadi ke pengomentar',
    /** What an agent starts from, editable before sending. The same default
     * the automatic sweep uses (FB_COMMENT_AUTO_REPLY_TEXT), so a reply sent
     * by hand and one sent by the sweep read the same on the post. */
    replyPublicDefault: 'Check DM ya kak!!!',
    /** Says who is writing and why before anything else — a Page's first
     * private message to a stranger reads as spam otherwise. */
    dmDefault: 'Halo kak, terima kasih sudah komentar. Ada yang bisa kami bantu? Balas di sini ya.',
    /** "Antrean", never "terkirim": a 202 means a job exists. The bridge still
     * has to type it into a real browser, and the status chip above is the
     * only thing that says whether the customer was actually answered. */
    replyQueued: 'Balasan publik masuk antrean. Status di atas diperbarui otomatis.',
    dmQueued: 'DM masuk antrean. Status di atas diperbarui otomatis.',
    processing: 'Sedang dikerjakan oleh sistem — tunggu sebentar.',
    replyPublicDone: 'Komentar ini sudah dibalas publik.',
    dmDone: 'DM ke pengomentar ini sudah terkirim.',
    dmNeedsReply: 'Balas publik dulu; DM baru bisa dikirim setelah balasan publik masuk.',
    replyFailed: 'Balasan publik gagal masuk antrean.',
    dmFailed: 'DM gagal masuk antrean.',
    emptyText: 'Isi pesannya dulu.',
    sending: 'Mengirim…',
    /** Fallback only. Nothing renders this any more — the actions are live in
     * `CommentActions` — but the key stays so anything that still reads it
     * gets a sentence rather than `undefined`. */
    actionsDisabled: 'Belum tersedia — backend balasan komentar belum diaktifkan.',

    commentStatuses: {
      new: 'Baru',
      public_reply_pending: 'Balasan publik diproses',
      public_replied: 'Sudah dibalas publik',
      dm_pending: 'DM diproses',
      dm_sent: 'DM terkirim',
      failed: 'Gagal',
    } as Record<string, string>,
    publicReplyAt: 'Dibalas publik',
    dmAt: 'DM terkirim',
    attempts: 'Percobaan',
    /** Named per step, because they fail independently and are stored
     * independently: an agent needs to see WHICH step did not happen. */
    publicReplyError: 'Balasan publik gagal',
    dmError: 'DM gagal',
    notFound: 'Komentar ini tidak ditemukan.',
    /** The left-list row for a post, grouped the way Meta Business Suite's own
     * "Facebook comments" tab does it: the post is the row, not whoever
     * commented on it. Facebook's own post id is the only name available
     * without scraping the post's own text or image, which this build does
     * not do — so it is shown plainly rather than invented a nicer one. */
    postLabel: (postId: string) => `Postingan ${postId}`,
    commentCount: (n: number) => `${n} komentar`,
    postThread: 'Semua komentar di postingan ini',
  },

  chatIg: {
    title: 'Chat IG',
    subtitle: 'Chat langsung dari akun Instagram yang terhubung — lewat API resmi Meta atau lewat login browser di server.',
    notConnected: 'Instagram belum terhubung.',
    goToSettings: 'Hubungkan di Pengaturan → Instagram',
  },

  chatFb: {
    title: 'Chat Facebook',
    subtitle: 'Chat langsung dari Messenger Halaman Facebook yang terhubung, lewat login browser di server.',
    notConnected: 'Facebook belum terhubung.',
    goToSettings: 'Hubungkan di Pengaturan → Facebook',
  },

  fbComments: {
    title: 'Komentar Facebook',
    subtitle: 'Komentar di postingan Facebook Anda. Balasan publik dibuat singkat — penjelasan lengkapnya lewat DM.',
    tabPending: 'Perlu dibalas',
    empty: 'Belum ada komentar masuk.',
  },

  waBridge: {
    title: 'Chat WA',
    subtitle: 'Chat langsung dari nomor WhatsApp pribadi Anda, dipindai lewat kode QR — bukan nomor bisnis resmi.',
    warning:
      'Ini memakai WhatsApp Web, bukan jalur resmi Meta. WhatsApp bisa memblokir nomor yang dipakai kirim pesan massal atau balasan otomatis berlebihan. Cocok untuk chat manual dulu.',
    sessions: 'Nomor tersambung',
    addNumber: 'Sambungkan nomor baru',
    namePlaceholder: 'Nama nomor ini, misal: WA Toko 1',
    connect: 'Sambungkan',
    connecting: 'Menyambungkan…',
    cancel: 'Batal',
    scanQr: 'Kode QR untuk disambungkan',
    scanHow: 'Buka WhatsApp di HP → Perangkat Tertaut → Tautkan Perangkat, arahkan kamera ke kode ini.',
    disconnect: 'Putuskan',
    delete: 'Hapus',
    deleteTitle: 'Hapus nomor ini?',
    deleteWarning: (name: string) =>
      `Ini akan menghapus "${name}" beserta semua riwayat percakapan dan pesannya secara permanen. Tindakan ini tidak bisa dibatalkan.`,
    deleteConfirm: 'Ya, hapus permanen',
    reconnect: 'Sambungkan ulang',
    manage: 'Kelola nomor',
    noSessions: 'Belum ada nomor WhatsApp yang tersambung.',
    failed: 'Gagal menyambungkan nomor',
    status: {
      starting: 'Memulai…', qr_pending: 'Menunggu dipindai', authenticated: 'Autentikasi berhasil',
      ready: 'Tersambung', disconnected: 'Terputus', logged_out: 'Diputuskan', error: 'Gagal',
      connecting: 'Menyambungkan', connected: 'Tersambung', disabled: 'Nonaktif',
    } as Record<string, string>,
    filteringNumber: (name: string) => `Nomor: ${name}`,
    clearFilter: 'Lihat semua nomor',
    chattingFrom: 'Chat dari',
    unknownNumber: 'Nomor tidak diketahui',
  },

  waChannel: {
    title: 'Channel WhatsApp',
    subtitle: 'Sambungkan dan kelola nomor WhatsApp Web di sini — begitu tersambung, langsung dipakai di halaman Chat WA tanpa perlu disambungkan ulang di sana.',
    name: 'Nama',
    phone: 'No HP',
    noPhone: 'Belum ada nomor',
    status: 'Status',
    actions: 'Aksi',
    viewQr: 'Lihat QR',
    noChannels: 'Belum ada nomor WhatsApp yang tersambung. Klik "Sambungkan" untuk menambahkan.',
    maxPerDay: 'Maks/Hari',
    maxPerDaySave: 'Simpan',
    maxPerDaySaved: 'Tersimpan.',
    maxPerDayFailed: 'Gagal menyimpan batas harian',
    statusChat: 'Status Chat',
    chatLabel: {
      meeting: 'Meeting', minat: 'Minat', balas: 'Balas', belum: 'Belum', tolak: 'Tolak', bot: 'Bot',
    } as Record<string, string>,
    totalChats: 'Jumlah Chat',
    chat: 'Chat',
    openChat: 'Buka Chat',
  },

  messageTemplate: {
    title: 'Template Pesan',
    subtitle: 'Template siap pakai untuk WhatsApp, Email, atau saluran lain — yang WhatsApp mengikuti aturan persetujuan Meta, yang lain bebas format.',
    hint: 'Pakai {{1}}, {{2}}, dst untuk variabel — sama seperti format template resmi WhatsApp.',
    searchPlaceholder: 'Cari nama atau isi template…',
    name: 'Nama Template',
    namePlaceholder: 'konfirmasi_pesanan',
    channel: 'Jenis',
    channelLabel: {
      whatsapp: 'WhatsApp', email: 'Email', other: 'Lainnya',
    } as Record<string, string>,
    channelHint: 'Template WhatsApp mengikuti alur persetujuan Meta (kategori & status di bawah). Email/Lainnya tidak perlu itu.',
    category: 'Kategori',
    categoryLabel: {
      marketing: 'Marketing', utility: 'Utility', authentication: 'Autentikasi',
    } as Record<string, string>,
    language: 'Bahasa',
    body: 'Isi Template',
    bodyPlaceholder: 'Halo {{1}}, pesanan Anda dengan kode {{2}} sudah kami proses.',
    status: 'Status Persetujuan',
    statusLabel: {
      draft: 'Draf', pending: 'Menunggu Review', approved: 'Disetujui', rejected: 'Ditolak',
    } as Record<string, string>,
    notes: 'Catatan',
    notesPlaceholder: 'Nomor pengajuan, alasan ditolak, dll (opsional)',
    add: 'Tambah Template',
    detail: 'Detail',
    detailTitle: 'Detail Template',
    newTitle: 'Template Baru',
    edit: 'Edit',
    delete: 'Hapus',
    deleteTitle: 'Hapus template ini?',
    deleteWarning: (name: string) => `Template "${name}" akan dihapus permanen. Tindakan ini tidak bisa dibatalkan.`,
    deleteConfirm: 'Ya, hapus',
    discard: 'Batal',
    close: 'Tutup',
    save: 'Simpan',
    saving: 'Menyimpan…',
    remove: 'Hapus',
    actions: 'Aksi',
    empty: 'Belum ada template. Tambahkan template pertama di sini.',
    noMatches: 'Tidak ada template yang cocok dengan pencarian ini.',
    failed: 'Gagal menyimpan template',
  },

  quickReply: {
    title: 'Balasan Cepat',
    subtitle: 'Kalimat singkat yang sering dipakai CS — tinggal klik untuk ditempel ke kotak chat. Beda dengan Template Pesan: ini bebas diedit siapa saja dan hanya bisa dipakai selama masih dalam jendela 24 jam.',
    name: 'Judul',
    namePlaceholder: 'Tanya ukuran',
    body: 'Isi Pesan',
    bodyPlaceholder: 'Untuk ukuran, kami ada S, M, L, XL kak. Mau yang mana?',
    shortcut: 'Kode (opsional)',
    shortcutPlaceholder: 'ukuran',
    add: 'Tambah Balasan',
    save: 'Simpan',
    saving: 'Menyimpan…',
    remove: 'Hapus',
    empty: 'Belum ada balasan cepat. Tambahkan yang sering dipakai tim di sini.',
    failed: 'Gagal menyimpan balasan cepat',
  },

  broadcast: {
    title: 'Broadcast',
    subtitle: 'Kirim satu template WhatsApp yang sudah disetujui ke banyak client sekaligus, berdasarkan tag.',
    add: 'Broadcast Baru',
    name: 'Nama Broadcast',
    namePlaceholder: 'Contoh: Promo Akhir Bulan',
    channel: 'Kirim dari Nomor',
    chooseChannel: 'Pilih nomor…',
    template: 'Template',
    chooseTemplate: 'Pilih template…',
    templateEmpty: 'Belum ada template yang disetujui (approved). Tambahkan dulu di halaman Template Pesan.',
    tags: 'Tag Client',
    tagsPlaceholder: 'reseller, grosir',
    tagsHint: 'Pisahkan dengan koma. Client dengan salah satu tag ini akan ditarget.',
    previewEligible: (n: number) => `${n} akan menerima`,
    previewNoConsent: (n: number) => `${n} dilewati — belum consent marketing`,
    previewNoConversation: (n: number) => `${n} dilewati — belum ada percakapan di nomor ini`,
    send: 'Kirim Broadcast',
    sending: 'Mengirim…',
    discard: 'Batal',
    failed: 'Gagal mengirim broadcast',
    columnTemplate: 'Template',
    columnChannel: 'Nomor',
    columnProgress: 'Terkirim',
    columnDate: 'Tanggal',
    detail: 'Detail',
    detailTitle: 'Detail Broadcast',
    close: 'Tutup',
    recipient: 'Client',
    recipientStatus: 'Status',
    recipientStatusLabel: {
      sent: 'Terkirim', delivered: 'Terkirim', read: 'Terkirim', queued: 'Menunggu',
      failed: 'Gagal', skipped: 'Dilewati',
    } as Record<string, string>,
    skippedReasonLabel: {
      no_consent: 'Belum consent marketing', no_conversation: 'Belum ada percakapan',
    } as Record<string, string>,
    empty: 'Belum ada broadcast. Kirim yang pertama di atas.',
  },

  document: {
    title: 'Dokumen',
    add: 'Tambah Dokumen',
    name: 'Nama',
    namePlaceholder: 'Contoh: Penawaran Batik Grosir',
    kind: 'Jenis',
    kindLabel: {
      penawaran: 'Penawaran', invoice: 'Invoice', kwitansi: 'Kwitansi', lainnya: 'Lainnya',
    } as Record<string, string>,
    addKind: 'Tambah Jenis Baru',
    addKindPlaceholder: 'Nama jenis, misal: Kontrak',
    addKindFailed: 'Gagal menambah jenis',
    model: 'Model',
    modelLabel: {
      standar: 'Standar',
    } as Record<string, string>,
    addModel: 'Tambah Model Baru',
    addModelPlaceholder: 'Nama model, misal: Formal',
    addModelFailed: 'Gagal menambah model',
    useTemplate: 'Template',
    useTemplateYes: 'Ya',
    useTemplateNo: 'Tidak',
    generate: 'Unduh (.docx)',
    generateFailed: 'Gagal membuat dokumen',
    actions: 'Aksi',
    detail: 'Detail',
    delete: 'Hapus',
    deleteTitle: 'Hapus dokumen ini?',
    deleteWarning: (name: string) => `Dokumen "${name}" akan dihapus permanen. Tindakan ini tidak bisa dibatalkan.`,
    deleteConfirm: 'Ya, hapus',
    discard: 'Batal',
    newTitle: 'Dokumen Baru',
    detailTitle: 'Detail Dokumen',
    close: 'Tutup',
    save: 'Simpan',
    saving: 'Menyimpan…',
    failed: 'Gagal menyimpan dokumen',
    empty: 'Belum ada dokumen. Tambahkan dokumen pertama di bawah.',

    editLayout: 'Kustomisasi Tampilan',
    editorTitle: 'Kustomisasi Tampilan',
    backToDetail: 'Kembali',
    addText: 'Tambah Teks',
    addLogo: 'Tambah Logo',
    uploadReference: 'Upload Referensi (.docx)',
    uploadReferenceHint: 'Ambil gambar yang ada di dalam file .docx ini untuk dipakai sebagai logo.',
    uploadReferenceEmpty: 'Tidak ada gambar yang ditemukan di file ini.',
    uploadReferenceFailed: 'Gagal membaca file .docx',
    fixedText: 'Teks tetap',
    autoData: 'Data otomatis',
    mergeFieldLabel: {
      tenant_name: 'Nama Toko', document_name: 'Nama Dokumen',
    } as Record<string, string>,
    fontSize: 'Ukuran Teks',
    bold: 'Tebal',
    removeElement: 'Hapus elemen',
    editorSaved: 'Tampilan tersimpan',
    editorFailed: 'Gagal menyimpan tampilan',
    selectElementHint: 'Klik salah satu elemen untuk mengaturnya.',

    pageSetup: 'Ukuran Kertas & Margin',
    pageSize: 'Ukuran Kertas',
    pageSizeLabel: {
      a4: 'A4', letter: 'Letter', legal: 'Legal', f4: 'F4 (Folio)',
    } as Record<string, string>,
    marginTop: 'Margin Atas',
    marginRight: 'Margin Kanan',
    marginBottom: 'Margin Bawah',
    marginLeft: 'Margin Kiri',
    marginUnit: 'mm',

    addRichText: 'Tambah Paragraf',
    richTextPlaceholder: 'Mulai ketik di sini…',
    insertMergeField: 'Sisipkan Data Otomatis',
    boldTip: 'Tebal',
    italicTip: 'Miring',
    bulletTip: 'Daftar Poin',
    headingTip: 'Judul',
  },

  waStatus: {
    title: 'Status Nomor',
    subtitle: 'Semua nomor WhatsApp yang tersambung, dan berapa chat yang masih menunggu dibalas di masing-masing.',
    code: 'Kode',
    number: 'Nomor',
    totalChats: 'Jumlah Chat',
    todayChats: 'Chat Hari Ini',
    lastActive: 'Terakhir Aktif',
    neverActive: 'Belum ada chat',
    status: 'Status',
    unanswered: 'Belum Dijawab',
    unansweredCount: (n: number) => n === 0 ? 'Tidak ada' : `${n} chat`,
    queue: 'Antrian',
    queueCount: (n: number) => n === 0 ? 'Kosong' : `${n} belum dipegang`,
    avgReply: 'Rata-rata Waktu Balas',
    avgReplyNone: 'Belum ada balasan',
    noNumbers: 'Belum ada nomor WhatsApp yang tersambung.',
  },

  agentPerformance: {
    title: 'Performa Agen',
    subtitle: 'Ringkasan kinerja tim membalas chat.',

    statActive: 'Agen Aktif',
    statAvgReply: 'Rata-rata Waktu Balas',
    statHandled: 'Obrolan Ditangani Hari Ini',
    statResolution: 'Tingkat Penyelesaian',

    panelHandled: 'Obrolan Ditangani per Agen',
    panelResolution: 'Tingkat Penyelesaian per Agen',
    panelRings: 'Ringkasan Performa Tim',
    panelRingsNote: 'Tiap garis satu ukuran nyata: obrolan terjawab, tingkat selesai, dan kecepatan balas.',
    ringChat: 'Terjawab',
    ringRespon: 'Selesai',
    ringSpeed: 'Kecepatan',
    panelRingsPerAgent: 'Skor Performa per Agen',
    panelRingsPerAgentNote: 'Sama seperti di atas, dipecah per agen. Angka di tengah adalah rata-rata ketiga ukuran.',
    ringScoreLabel: 'Skor',
    panelDetail: 'Detail Performa Agen',

    tableAgent: 'Agen',
    tableHandled: 'Ditangani',
    tableWaiting: 'Perlu Dibalas',
    tableAvgReply: 'Rata-rata Waktu Balas',
    tableResolution: 'Tingkat Penyelesaian',
  },

  contact: {
    title: 'Contact',
    comingSoon: 'Halaman ini belum ada isinya.',
  },

  automation: {
    workflowTitle: 'Workflow',
    workflowSubtitle: 'Otomatiskan pekerjaan berulang — data contoh, belum tersambung ke data asli.',
    dummyBadge: 'Data contoh',
    add: '+ Workflow Baru',
    addDisabledHint: 'Pembuatan workflow baru segera hadir',
    columnName: 'Nama Workflow',
    columnTrigger: 'Pemicu',
    columnAction: 'Aksi',
    columnStatus: 'Status',
    columnRuns: 'Dijalankan',
    columnLastRun: 'Terakhir Jalan',
    detail: 'Detail',
    statusActive: 'Aktif',
    statusInactive: 'Nonaktif',
    statusToggleHint: 'Klik untuk mengubah status (contoh, tidak tersimpan)',
    stepTrigger: 'Pemicu',
    stepConditions: 'Kondisi',
    stepActions: 'Aksi',
    runCountLabel: (n: number) => `Sudah berjalan ${n}x`,
    lastRunLabel: (ago: string) => `Terakhir dijalankan ${ago} lalu`,

    backToList: '← Daftar Workflow',
    removeNode: 'Hapus Node',
    cannotRemoveTrigger: 'Pemicu tidak bisa dihapus — setiap workflow butuh satu pemicu.',
    nodeTitleField: 'Judul',
    nodeLabelField: 'Deskripsi',
    save: 'Simpan',
    editorSaved: 'Tersimpan (pratinjau — belum tersambung ke server)',
    chooseAction: 'Pilih Langkah',
    searchActions: 'Cari aksi atau kondisi…',
    noActionsFound: 'Tidak ditemukan.',
  },

  dashboard: {
    title: 'Dashboard',
    subtitle: 'Ringkasan toko Anda. Data contoh — belum tersambung ke angka asli.',
    dummyNote: 'Data contoh',

    statClients: 'Total Client',
    statClientsDelta: '+12 minggu ini',
    statUnanswered: 'Obrolan Perlu Dibalas',
    statUnansweredDelta: '-3 dari kemarin',
    statSales: 'Penjualan Bulan Ini',
    statSalesDelta: '+18% dari bulan lalu',
    statReplyTime: 'Rata-rata Waktu Balas',
    statReplyTimeDelta: '-2 menit dari kemarin',

    panelDaily: 'Obrolan Masuk — 7 Hari Terakhir',
    panelChannels: 'Saluran Teraktif',
    panelPipeline: 'Pipa Penjualan',
    panelRecent: 'Client Terbaru',

    days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'],

    tableName: 'Nama',
    tablePhone: 'Nomor',
    tableTag: 'Label',
    tableWhen: 'Ditambahkan',
  },

  timeline: {
    title: 'Riwayat Aktivitas',
    empty: 'Belum ada aktivitas tercatat untuk client ini.',
    openChat: 'Buka Obrolan',
  },

  activities: {
    title: 'Aktivitas',
    upcoming: 'Akan Datang',
    empty: 'Belum ada tugas untuk client ini.',
    assignedTo: (name: string) => `Tugas untuk ${name}`,
    overdue: (date: string) => `Terlambat: ${date}`,
    due: (date: string) => `Jatuh tempo: ${date}`,
    cancelled: (date: string) => `Dibatalkan: ${date}`,
  },

  client: {
    title: 'Client',
    subtitle: 'Orang-orang yang sudah ditandai sebagai client, dari chat maupun ditambah manual.',
    titleDeal: 'Client Deal',
    subtitleDeal: 'Client dengan status Deal.',
    noClientsDeal: 'Belum ada client dengan status Deal.',
    titleProses: 'Client On Proses',
    subtitleProses: 'Client dengan status On Progress.',
    noClientsProses: 'Belum ada client on proses.',
    name: 'Nama',
    phone: 'Nomor',
    email: 'Email',
    igUsername: 'Username Instagram',
    clientStatus: 'Status',
    clientStatusLabel: { on_progress: 'On Progress', deal: 'Deal' } as Record<string, string>,
    tags: 'Label',
    tagsHint: 'Pisahkan dengan koma, misal: vip, grosir',
    address: 'Alamat',
    addressPlaceholder: 'Jalan, kota, kode pos',
    notes: 'Catatan',
    notesPlaceholder: 'Catatan internal soal client ini',
    storeName: 'Nama Toko',
    storeNamePlaceholder: 'Nama toko/usaha client',
    storeStatus: 'Status Toko',
    storeStatusPlaceholder: 'Pilih status',
    storeStatusLabel: { prospek: 'Prospek', aktif: 'Aktif', nonaktif: 'Tidak Aktif' } as Record<string, string>,
    scheduleMeeting: 'Jadwal Meeting',
    scheduleMeetingHint: 'Otomatis tersimpan sebagai tugas Meeting, dan masuk Google Calendar kalau sudah terhubung.',
    scheduleMeetingFormTitle: 'Kalender Baru',
    scheduleMeetingDateLabel: 'Tanggal',
    meetingDetailTitle: 'Detail Meeting',
    meetingCalendarLinkLabel: 'Link Google Calendar',
    meetingCalendarLinkNotSynced: 'Belum masuk Google Calendar',
    lastSeen: 'Terakhir Aktif',
    chat: 'Chat',
    noChat: 'Belum ada obrolan dengan client ini',
    noClients: 'Belum ada client. Tandai dari halaman chat, atau tambah manual.',
    add: 'Tambah Client',
    detail: 'Detail',
    detailTitle: 'Detail Client',
    openFullPage: 'Buka halaman lengkap',
    edit: 'Edit',
    actions: 'Aksi',
    photoUpload: 'Unggah foto client',
    photoChange: 'Ubah foto',
    searchPlaceholder: 'Cari nama, nomor, atau label…',
    filters: 'Filters',
    groupBy: 'Group By',
    noFilters: 'Belum ada label untuk difilter',
    noGroup: 'Tidak dikelompokkan',
    groupByTag: 'Label',
    noLabel: 'Tanpa label',
    noMatches: 'Tidak ada client yang cocok dengan pencarian/filter ini.',
    newClient: 'Client Baru',
    namePlaceholder: 'Nama client',
    save: 'Simpan',
    saving: 'Menyimpan…',
    discard: 'Batal',
    delete: 'Hapus',
    deleteTitle: 'Hapus client ini?',
    deleteWarning: (name: string) =>
      `"${name}" akan disembunyikan dari daftar Client. Data dan riwayat chat-nya tetap tersimpan, tidak benar-benar hilang.`,
    deleteConfirm: 'Ya, hapus',
    phoneMaskedHint: 'Nomor disamarkan — cuma yang punya akses lihat nomor penuh yang bisa mengubahnya.',
    saved: 'Tersimpan',
    failed: 'Gagal menyimpan data client',
    notFound: 'Client ini tidak ditemukan — mungkin sudah dihapus.',
    purchases: {
      title: 'Riwayat Pembelian',
      column: 'Total Pembelian',
      count: 'Jumlah',
      empty: 'Belum pernah belanja.',
      itemsFallback: '—',
    },
  },

  brand: {
    title: 'Tracker Brand',
    subtitle: 'Daftar brand yang mau dihubungi untuk kerja sama — hasil scrape maupun ditambah manual.',
    searchPlaceholder: 'Cari nama brand, PIC, atau kota…',
    add: 'Tambah Brand',
    newBrand: 'Brand Baru',
    namePlaceholder: 'Nama brand',
    name: 'Nama Brand',
    picName: 'Nama PIC',
    picNamePlaceholder: 'Nama contact person di brand ini',
    phone: 'No WhatsApp',
    email: 'Email',
    instagram: 'Instagram',
    instagramPlaceholder: '@namabrand',
    website: 'Website',
    category: 'Kategori',
    categoryPlaceholder: 'Misal: Fashion, F&B, Skincare',
    city: 'Kota',
    source: 'Sumber Data',
    sourceHint: 'Dari mana data ini didapat — supaya jelas mana hasil scrape otomatis dan mana yang ditambah manual.',
    sourceLabel: {
      scrape: 'Hasil Scrape', manual: 'Input Manual', referral: 'Referral', other: 'Lainnya',
    } as Record<string, string>,
    status: 'Status',
    statusLabel: {
      not_contacted: 'Belum Dihubungi', contacted: 'Sudah Dihubungi', replied: 'Sudah Reply',
      interested: 'Minat', rejected: 'Nolak',
    } as Record<string, string>,
    filterAll: 'Semua',
    filterNotContacted: 'Belum Dihubungi',
    filterContacted: 'Sudah Dihubungi',
    filterReplied: 'Sudah Reply',
    filterInterested: 'Minat',
    filterRejected: 'Nolak',
    markContacted: 'Tandai Dihubungi',
    markReplied: 'Tandai Sudah Reply',
    markInterested: 'Tandai Minat',
    markRejected: 'Tandai Nolak',
    assignee: 'CS yang Menangani',
    unassigned: 'Belum ditugaskan',
    notes: 'Catatan',
    notesPlaceholder: 'Catatan internal soal brand ini',
    lastContacted: 'Terakhir Dihubungi',
    neverContacted: 'Belum pernah',
    actions: 'Aksi',
    edit: 'Edit',
    save: 'Simpan',
    saving: 'Menyimpan…',
    discard: 'Batal',
    delete: 'Hapus',
    deleteTitle: 'Hapus brand ini?',
    deleteWarning: (name: string) => `Brand "${name}" akan dihapus permanen dari daftar outreach. Tindakan ini tidak bisa dibatalkan.`,
    deleteConfirm: 'Ya, hapus',
    chat: 'Chat',
    openChat: 'Buka Chat WhatsApp',
    noPhoneForChat: 'Belum ada nomor WhatsApp',
    chatFailed: 'Gagal membuka chat',
    exportExcel: 'Ekspor Excel',
    exporting: 'Mengekspor…',
    dateAll: 'Semua Tanggal',
    dateToday: 'Hari Ini',
    date7d: '7 Hari',
    date30d: '30 Hari',
    dateCustom: 'Rentang Tanggal',
    dateMonth: 'Bulan Tertentu',
    dateYear: 'Tahun Tertentu',
    dateYearRange: 'Rentang Tahun',
    dateFrom: 'Dari',
    dateTo: 'Sampai',
    exportSheetName: 'Brand',
    exportColName: 'Nama',
    exportColPic: 'PIC',
    exportColPhone: 'Telepon',
    exportColEmail: 'Email',
    exportColInstagram: 'Instagram',
    exportColCategory: 'Kategori',
    exportColCity: 'Kota',
    exportColSource: 'Sumber',
    exportColStatus: 'Status',
    exportColAssignee: 'CS yang Menangani',
    exportColLastContacted: 'Terakhir Dihubungi',
    exportColCreated: 'Dibuat',
    noBrands: 'Belum ada brand. Tambahkan hasil scrape atau brand incaran secara manual.',
    noMatches: 'Tidak ada brand yang cocok dengan pencarian/filter ini.',
    failed: 'Gagal menyimpan data brand',
    notFound: 'Brand ini tidak ditemukan — mungkin sudah dihapus.',
  },

  brandManagement: {
    title: 'Kelola Brand',
    tableTitle: 'Data Brand',
    statusHint: 'Status funnel diatur dari Tracker Brand.',
    importTitle: 'Import Brand',
    importHint: 'Unggah file Excel atau CSV berisi daftar brand. Kolom yang dikenali: Nama, PIC, Telepon, Email, Instagram, Website, Kategori, Kota, Sumber. Cuma kolom Nama yang wajib diisi.',
    downloadTemplate: 'Unduh Template',
    chooseFile: 'Pilih File',
    changeFile: 'Ganti File',
    noFileChosen: 'Belum ada file dipilih',
    parsing: 'Membaca file…',
    parseFailed: 'File tidak bisa dibaca — pastikan formatnya .xlsx, .xls, atau .csv',
    noRows: 'Tidak ada baris yang bisa diimpor dari file ini',
    previewTitle: (n: number) => `${n} baris siap diimpor`,
    previewMore: (n: number) => `+${n} baris lagi tidak ditampilkan`,
    skippedTitle: (n: number) => `${n} baris dilewati (kolom Nama kosong)`,
    rowLabel: (n: number) => `Baris ${n}`,
    importButton: (n: number) => `Import ${n} Brand`,
    importing: 'Mengimpor…',
    importFailed: 'Gagal mengimpor brand',
    importResultCreated: (n: number) => `${n} brand berhasil ditambahkan.`,
    importResultSkippedByServer: (n: number) => ` ${n} baris dilewati server.`,
    startOver: 'Import File Lain',
    templateSheetName: 'Template Brand',
    col: {
      name: 'Nama', picName: 'PIC', phone: 'Telepon', email: 'Email', instagram: 'Instagram',
      website: 'Website', category: 'Kategori', city: 'Kota', source: 'Sumber',
    },
  },

  orders: {
    title: 'Pesanan',
    subtitle: 'Semua pesanan dari chat, mulai dari draf sampai terkirim.',
    searchPlaceholder: 'Cari kode pesanan, nama, atau nomor…',
    filterAll: 'Semua',
    filterDraft: 'Draf',
    filterAwaiting: 'Menunggu Bayar',
    filterPaid: 'Sudah Dibayar',
    filterFulfilled: 'Terkirim',
    filterCancelled: 'Dibatalkan',
    code: 'Kode',
    client: 'Client',
    items: 'Item',
    itemsCount: (n: number) => `${n} item`,
    total: 'Total',
    area: 'Area Kirim',
    created: 'Dibuat',
    status: 'Status',
    actions: 'Aksi',
    statusLabel: {
      draft: 'Draf',
      awaiting_payment: 'Menunggu Bayar',
      paid: 'Sudah Dibayar',
      fulfilled: 'Terkirim',
      cancelled: 'Dibatalkan',
    } as Record<string, string>,
    markPaid: 'Tandai Dibayar',
    fulfill: 'Tandai Terkirim',
    cancel: 'Batalkan',
    cancelTitle: 'Batalkan pesanan ini?',
    cancelWarning: (code: string) =>
      `Pesanan "${code}" akan dibatalkan dan stok yang sudah dikunci dikembalikan. Tindakan ini tidak bisa dibatalkan.`,
    cancelConfirm: 'Ya, batalkan',
    discard: 'Tutup',
    noArea: '—',
    empty: 'Belum ada pesanan. Pesanan muncul di sini setelah dibuat dari sebuah obrolan.',
    noMatches: 'Tidak ada pesanan yang cocok dengan pencarian/filter ini.',
  },

  tasks: {
    title: 'Tugas',
    subtitle: 'Follow-up dan pengingat untuk client.',
    add: 'Tambah Tugas',
    searchPlaceholder: 'Cari tugas atau nama client…',
    filterAll: 'Semua',
    filterDue: 'Perlu Ditindaklanjuti',
    filterDone: 'Selesai',
    filterCancelled: 'Dihapus',
    taskTitle: 'Tugas',
    contact: 'Client',
    dueAt: 'Jatuh Tempo',
    assignee: 'Ditugaskan ke',
    unassigned: 'Belum ditugaskan',
    status: 'Status',
    actions: 'Aksi',
    statusLabel: {
      open: 'Berjalan', done: 'Selesai', cancelled: 'Dihapus',
    } as Record<string, string>,
    kind: 'Jenis',
    kindLabel: {
      follow_up: 'Follow-up', call: 'Telepon', meeting: 'Meeting', chat: 'Pesan', email: 'Email', other: 'Lainnya',
    } as Record<string, string>,
    priority: 'Prioritas',
    priorityLabel: {
      low: 'Rendah', medium: 'Sedang', high: 'Tinggi', urgent: 'Mendesak',
    } as Record<string, string>,
    repeat: 'Ulangi Tugas',
    repeatNone: 'Tidak berulang',
    repeatUnitLabel: {
      day: 'Hari', week: 'Minggu', month: 'Bulan', year: 'Tahun',
    } as Record<string, string>,
    repeatEvery: 'Setiap',
    repeatUntil: 'Berulang sampai',
    repeatUntilHint: 'Kosongkan untuk berulang terus',
    repeatBadge: (unit: string, interval: number) =>
      interval > 1 ? `↻ setiap ${interval} ${t.tasks.repeatUnitLabel[unit]?.toLowerCase()}` : `↻ ${t.tasks.repeatUnitLabel[unit]?.toLowerCase()}an`,
    joinMeeting: 'Gabung Meeting',
    viewInGoogleCalendar: 'Lihat di Google Calendar',
    overdue: 'Lewat jatuh tempo',
    dueToday: 'Hari ini',
    markDone: 'Tandai Selesai',
    cancel: 'Hapus',
    cancelTitle: 'Hapus tugas ini?',
    cancelWarning: (title: string) => `Tugas "${title}" akan dihapus. Tindakan ini tidak bisa diurungkan.`,
    cancelConfirm: 'Ya, hapus',
    discard: 'Batal',
    empty: 'Belum ada tugas. Tambahkan pengingat follow-up untuk client Anda.',
    noMatches: 'Tidak ada tugas yang cocok dengan pencarian/filter ini.',

    newTitle: 'Tugas Baru',
    detail: 'Detail',
    detailTitle: 'Detail Tugas',
    // The Kalender page's own wording for the same add/detail drawers — Tugas
    // keeps calling them tasks, Kalender calls them schedule entries. Same
    // form, same server action, just a label a person reads.
    addSchedule: 'Tambah Jadwal',
    newScheduleTitle: 'Jadwal Baru',
    detailScheduleTitle: 'Detail Jadwal',
    sendEmail: 'Kirim Email',
    sendEmailTitle: 'Kirim undangan meeting lewat email',
    sendEmailTo: 'Alamat email',
    sendingEmail: 'Mengirim…',
    sendEmailFailed: 'Gagal mengirim email',
    formTitle: 'Judul',
    titlePlaceholder: 'Contoh: Follow-up penawaran batik parang',
    formContact: 'Client',
    chooseContact: 'Pilih client…',
    formBrand: 'Brand',
    chooseBrand: 'Pilih brand…',
    noBrands: 'Belum ada brand. Tambahkan brand dulu di halaman Tracker Brand.',
    formDueAt: 'Jatuh Tempo',
    formAssignee: 'Ditugaskan ke',
    formDeal: 'Deal terkait',
    noDeal: 'Tidak ada',
    formKind: 'Jenis',
    addKind: 'Tambah Jenis Baru',
    addKindPlaceholder: 'Nama jenis, misal: Survei Lokasi',
    addKindFailed: 'Gagal menambah jenis',
    formPriority: 'Prioritas',
    formMeetingLink: 'Link Video Conference',
    meetingLinkPlaceholder: 'https://meet.google.com/xxx-yyyy-zzz',
    formNotes: 'Catatan',
    notesPlaceholder: 'Detail tambahan (opsional)',
    save: 'Simpan',
    saving: 'Menyimpan…',
    failed: 'Gagal menyimpan tugas',
    close: 'Tutup',

    viewTable: 'Tabel',
    viewKanban: 'Kanban',
    viewCalendar: 'Kalender',
    moreCount: (n: number) => `+${n} lainnya`,
    todayLabel: 'Hari ini',
    prevMonth: 'Bulan sebelumnya',
    nextMonth: 'Bulan berikutnya',
    calendarEmpty: 'Tidak ada tugas jatuh tempo pada periode ini.',
    googleConnect: 'Hubungkan Google Calendar',
    googleConnected: 'Google Calendar tersambung',
    disconnectHint: 'Klik untuk memutus sambungan',
    closeNotice: 'Tutup',
    googleConnectedNotice: 'Google Calendar berhasil tersambung. Acara Anda akan muncul di tampilan Kalender, List, dan Kanban.',
    googleConnectFailed: 'Gagal menyambungkan Google Calendar.',
    googleUpcomingEmpty: 'Tidak ada acara dalam 30 hari ke depan.',
    googleColumn: 'Google Calendar',
    // `googleSource` labels a row that has no task behind it at all — an
    // event pulled straight from Google, read-only, nothing in this
    // database. A task that is ALSO on Google gets two chips instead of one
    // ("Tersambung Google Calendar" read as if the row itself were sourced
    // from Google, next to its own Detail/Tandai Selesai/Hapus buttons,
    // confirmed confusing live) — `crmLabel` for the row that lives here,
    // `googleSource` reused for the event that also lives there. See
    // `SyncBadges`.
    googleSource: 'Google Calendar',
    crmLabel: 'CRM',
    /** Plain-text equivalent for a native `title` tooltip, which cannot
     *  render two coloured chips — the pills in Bulan/Hari/Minggu use this. */
    crmAndGoogle: 'CRM + Google Calendar',
    openInGoogle: 'Buka di Google',
    googleEventDetailTitle: 'Detail Acara Google Calendar',
    source: 'Sumber',
    allDay: 'Sepanjang hari',

    viewDay: 'Hari',
    viewWeek: 'Minggu',
    viewMonth: 'Bulan',
    viewYear: 'Tahun',
    // The second toolbar toggle — how the currently-anchored period renders,
    // as opposed to `viewDay/Week/Month` above (which period). "Grid Bulan"
    // only ever shows next to Bulan mode, since Hari/Minggu already have
    // their own hourly grid and don't need a second way to look at the same
    // few hours.
    contentViewGrid: 'Grid Bulan',
    contentViewAgenda: 'Agenda',
    contentViewTimeline: 'Timeline',
    contentViewTimelineSoon: 'Timeline: belum tersedia — tugas hanya menyimpan jam mulai, belum ada durasi untuk digambar sebagai batang waktu.',
    prevPeriod: 'Sebelumnya',
    nextPeriod: 'Berikutnya',
    filtersLabel: 'Filter Status',
    resetFilters: 'Reset',
    todayScheduleTitle: (date: string) => `Agenda Hari Ini (${date})`,
    todayScheduleCount: (n: number) => `${n} Jadwal`,
    monthAgendaEmpty: 'Tidak ada jadwal bulan ini.',
    todayScheduleEmpty: 'Tidak ada jadwal hari ini.',
    googleMeetBadge: 'Google Meet',
  },
};
