/**
 * Every word the user reads, in one file.
 *
 * Two rules were applied to all of it:
 *   1. Bahasa Indonesia, the way a shop supervisor in Jakarta actually talks —
 *      not translated software English.
 *   2. No jargon. "Overage" became "biaya tambahan", "resolve" became "tandai
 *      selesai", "conversation window" became "sudah lewat 24 jam". Where a rule
 *      comes from WhatsApp rather than from us, the copy says so, because a
 *      person who understands *why* stops being afraid of the button.
 *
 * Keeping it in one place means the plain-language pass can be reviewed by
 * someone who does not read React.
 */
export const t = {
  app: {
    name: 'Kirana',
    tagline: 'Semua chat pelanggan di satu tempat',
  },

  nav: {
    dashboard: 'Dashboard',
    chats: 'Obrolan',
    chatWa: 'Chat WA',
    customers: 'Pelanggan',
    orders: 'Pesanan',
    contact: 'Contact',
    monitoring: 'Monitoring',
    waStatus: 'Status Nomor',
    agentPerformance: 'Performa Agen',
    sales: 'Penjualan',
    team: 'Tim',
    settings: 'Pengaturan',
    signOut: 'Keluar',
  },

  roles: {
    owner: 'Pemilik',
    admin: 'Admin',
    supervisor: 'Supervisor',
    agent: 'Agen',
    viewer: 'Hanya lihat',
  } as Record<string, string>,

  roleNote: {
    owner: 'Bisa semua, termasuk tagihan dan menutup akun',
    admin: 'Bisa semua kecuali tagihan',
    supervisor: 'Bisa buka semua obrolan, bagi tugas, dan lihat nomor lengkap',
    agent: 'Hanya obrolan miliknya atau yang belum dipegang. Nomor pelanggan disamarkan',
    viewer: 'Hanya bisa melihat, tidak bisa membalas',
  } as Record<string, string>,

  login: {
    title: 'Masuk ke akun toko Anda',
    subtitle: 'Pakai nama akun yang dibuat oleh admin Anda.',
    shop: 'Nama akun toko',
    shopHint: 'Contoh: toko-demo',
    email: 'Email',
    password: 'Kata sandi',
    submit: 'Masuk',
    demo: 'COBA DULU',
    expired: 'Sesi Anda habis. Silakan masuk lagi.',
    wrong: 'Email atau kata sandi tidak cocok',
    tooMany: 'Terlalu banyak percobaan. Tunggu beberapa menit.',
    offline: 'Tidak bisa menghubungi server',
    incomplete: 'Semua kolom harus diisi',
    stale: 'Halaman ini sudah kedaluwarsa. Muat ulang lalu coba lagi.',
  },

  chats: {
    title: 'Obrolan',
    subtitle: 'Balas pelanggan di sini. Yang ada tanda kuning belum dibalas.',
    filterAll: 'Semua',
    filterNeedsReply: 'Perlu dibalas',
    filterDone: 'Selesai',
    needsReply: 'Menunggu balasan Anda',
    nobodyYet: 'Belum dipegang',
    done: 'Selesai',
    emptyList: 'Tidak ada obrolan di sini.',
    pickOne: 'Pilih satu obrolan di kiri',
    pickOneHelp: 'Obrolan paling baru ada di atas. Tanda kuning berarti pelanggan sedang menunggu balasan Anda.',
    live: 'Otomatis segarkan',
    paused: 'Berhenti sementara',
    updated: 'Diperbarui',
    refreshing: 'Memuat…',

    takeIt: 'Saya yang tangani',
    markCustomer: 'Tandai sebagai customer',
    markedCustomer: 'Customer',
    handledBy: 'Ditangani oleh',
    assign: 'Simpan',
    markDone: 'Tandai selesai',
    reopen: 'Sudah selesai',
    noOne: 'Belum ada',

    canReplyFreely: 'Bisa balas bebas',
    templateOnly: 'Sudah lewat 24 jam',
    windowClosedTitle: 'Pelanggan ini terakhir chat lebih dari 24 jam lalu',
    windowClosedBody:
      'Ini aturan dari WhatsApp, bukan dari kami: kalau sudah lewat 24 jam, balasan harus memakai pesan template yang sudah disetujui Meta. Tulis nama templatenya di bawah, lalu kirim.',
    templateName: 'Nama template',
    templateNameHint: 'contoh: konfirmasi_pesanan',
    writeReply: 'Tulis balasan…',
    writeTemplate: 'Isi pesan template…',
    send: 'Kirim balasan',
    sendTemplate: 'Kirim template',
    sending: 'Mengirim…',
    emptyMessage: 'Tulis pesannya dulu',
    sendFailed: 'Pesan gagal dikirim',
    freeform: 'Masih dalam 24 jam — boleh balas bebas',

    sender: {
      contact: 'Pelanggan',
      agent: 'Anda / tim',
      autopilot: 'Dijawab otomatis',
      system: 'Sistem',
    } as Record<string, string>,

    redacted: 'sudah dihapus',
    noMessages: 'Belum ada pesan.',

    aboutCustomer: 'Tentang pelanggan',
    name: 'Nama',
    phone: 'Nomor HP',
    lastChat: 'Terakhir chat',
    autoReply: 'Balasan otomatis',
    handling: 'Penanganan',
    status: 'Status',
    ordersHere: 'Pesanan',
    noOrders: 'Belum ada pesanan dari chat ini.',
    orderStatus: {
      draft: 'Sedang disusun', awaiting_payment: 'Menunggu bayar',
      paid: 'Sudah dibayar', cancelled: 'Dibatalkan', fulfilled: 'Sudah dikirim',
    } as Record<string, string>,
    salesHere: 'Penjualan',
    noSales: 'Belum ada penjualan untuk pelanggan ini.',
    inProgress: 'dalam proses',
    billingNote:
      'Satu pelanggan dihitung 1 obrolan per 24 jam, berapa pun jumlah pesannya.',
  },

  autopilot: {
    ready: 'Balasan otomatis sudah disiapkan',
    confidence: 'yakin',
    explain: 'Ini belum terkirim. Baca dulu, baru putuskan.',
    use: 'Pakai & kirim',
    edit: 'Ubah dulu',
    sendEdited: 'Kirim yang sudah diubah',
    cancelEdit: 'Batal',
    discard: 'Abaikan',
    working: 'Sebentar…',
    failed: 'Gagal memproses balasan otomatis',

    title: 'Balasan otomatis',
    subtitle: 'Seberapa jauh robot boleh menjawab sendiri, dan dari katalog mana dia menjawab.',
    mode: 'Cara kerja',
    modeOff: 'Mati',
    modeOffNote: 'Tidak menyiapkan apa pun.',
    modeSuggest: 'Siapkan draf saja',
    modeSuggestNote: 'Robot menulis, orang yang menekan kirim. Mulai dari sini.',
    modeAuto: 'Balas sendiri',
    modeAutoNote: 'Robot langsung membalas, tapi hanya kalau semua pemeriksaan lolos.',
    save: 'Simpan',
    saved: 'Tersimpan.',
    guardTitle: 'Yang selalu diperiksa sebelum terkirim',
    guards: [
      'Harga harus ada di katalog. Angka karangan langsung ditahan.',
      'Tidak boleh menjanjikan diskon atau tanggal barang pasti sampai.',
      'Tidak boleh bilang stok ada kalau di katalog stoknya nol.',
      'Pelanggan yang komplain selalu diserahkan ke orang.',
      'Kalau robot ragu, orang yang menjawab.',
    ],
    capTitle: 'Batas aman',
    capBody: (n: number) =>
      `Maksimal ${n} balasan otomatis per jam untuk seluruh toko. Kalau chat membanjir, robot berhenti dan orang yang lanjut — supaya biaya tidak lari.`,
    capOff: 'Tidak ada batas jumlah balasan otomatis per jam.',
    stats: 'Sebulan terakhir',
    statPending: 'Menunggu diperiksa',
    statUsed: 'Dipakai apa adanya',
    statEdited: 'Dipakai setelah diubah',
    statAuto: 'Dikirim sendiri',
    statBlocked: 'Ditahan pemeriksaan',
    statDiscarded: 'Dibuang',
    catalogue: 'Katalog & aturan',
    catalogueNote: 'Robot hanya boleh menjawab dari daftar ini. Kalau tidak ada di sini, dia menyerahkan ke orang.',
    kind: 'Jenis',
    itemTitle: 'Nama',
    sku: 'Kode',
    price: 'Harga',
    stock: 'Stok',
    emptyCatalogue: 'Katalog masih kosong. Selama kosong, robot tidak akan menjawab sendiri.',
    kinds: { product: 'Produk', faq: 'Tanya jawab', policy: 'Aturan' } as Record<string, string>,
  },

  /** Why a draft was held back, in words a supervisor can act on. */
  guardReasons: {
    ungrounded_price: 'Harga tidak ada di katalog',
    discount_not_allowed: 'Menjanjikan diskon',
    delivery_promise_not_allowed: 'Menjanjikan tanggal sampai',
    unknown_sku: 'Menyebut produk yang tidak ada',
    out_of_stock_claim: 'Bilang ada padahal stok habis',
    too_long: 'Balasan kepanjangan',
    empty_reply: 'Balasan kosong',
    external_link: 'Ada tautan asing',
    escalation_keyword: 'Pelanggan sedang komplain',
    low_confidence: 'Robot kurang yakin',
    model_asked_for_human: 'Robot minta dibantu orang',
    model_refused: 'Robot menolak menjawab',
    mode_off: 'Balasan otomatis sedang mati',
    mode_suggest: 'Mode siapkan draf',
  } as Record<string, string>,

  catalogue: {
    title: 'Katalog',
    subtitle: 'Robot hanya boleh menjawab dari daftar ini. Isi yang rapi di sini = jawaban yang benar di chat.',
    products: 'Produk',
    productsNote: 'Harga dan stok di sini yang dipakai robot untuk menjawab dan membuat pesanan.',
    name: 'Nama barang',
    sku: 'Kode',
    skuHint: 'contoh: KML-01',
    price: 'Harga',
    stock: 'Stok',
    note: 'Catatan',
    noteHint: 'warna, bahan, ukuran…',
    save: 'Simpan',
    saving: 'Menyimpan…',
    remove: 'Hapus',
    add: 'Tambah produk',
    addNote: 'Tambah tanya jawab / aturan',
    emptyProducts: 'Belum ada produk. Selama kosong, robot menyerahkan semua chat ke orang.',
    notes: 'Tanya jawab & aturan',
    notesNote: 'Hal yang sering ditanya: retur, cara bayar, jam kirim. Robot memakai ini apa adanya.',
    noteTitle: 'Judul',
    noteBody: 'Isi',
    kind: 'Jenis',
    kindFaq: 'Tanya jawab',
    kindPolicy: 'Aturan',
    emptyNotes: 'Belum ada catatan.',
    shipping: 'Ongkir',
    shippingNote: 'Tanpa ini robot tidak bisa menghitung total pesanan. Pakai "default" untuk daerah lain.',
    area: 'Daerah',
    cost: 'Biaya',
    eta: 'Estimasi hari',
    emptyShipping: 'Belum ada ongkir. Robot tidak akan bisa mengunci pesanan.',
    failed: 'Gagal menyimpan',
    saved: 'Tersimpan.',
  },

  security: {
    title: 'Keamanan',
    subtitle: 'Lapisan kedua supaya kata sandi saja tidak cukup untuk masuk.',
    twoStep: 'Verifikasi dua langkah',
    offNow: 'Belum aktif',
    onNow: 'Aktif',
    why: 'Kalau kata sandi Anda bocor, orang itu tetap tidak bisa masuk tanpa HP Anda. Sangat dianjurkan untuk Pemilik dan Admin.',
    turnOn: 'Nyalakan',
    step1: 'Buka aplikasi Google Authenticator atau Authy, pilih tambah akun, lalu masukkan kode di bawah ini.',
    secretLabel: 'Kunci untuk aplikasi',
    orOpen: 'Atau buka tautan ini di HP',
    step2: 'Masukkan 6 angka yang muncul di aplikasi',
    codeLabel: 'Kode 6 angka',
    confirm: 'Aktifkan',
    working: 'Sebentar…',
    cancel: 'Batal',
    turnOff: 'Matikan',
    turnOffHint: 'Masukkan kode dari aplikasi untuk mematikan',
    backupTitle: 'Kode cadangan',
    backupNote: 'Simpan sekarang. Kode ini hanya muncul sekali, dan dipakai kalau HP Anda hilang. Satu kode sekali pakai.',
    backupLeft: (n: number) => `${n} kode cadangan tersisa`,
    codeWrong: 'Kode tidak cocok. Cek jam di HP Anda, lalu coba lagi.',
    failed: 'Gagal memproses',

    eventsTitle: 'Kejadian keamanan',
    eventsNote: 'Hal-hal yang perlu dilihat orang. Yang bertanda merah punya batas waktu lapor.',
    eventsEmpty: 'Belum ada kejadian. Ini kabar baik.',
    clocksRunning: (n: number) => `${n} perlu dilaporkan`,
    kinds: {
      audit_chain_broken: 'Catatan riwayat diubah dari luar aplikasi',
      cross_tenant_denied: 'Ada yang mencoba membuka data toko lain',
      refresh_token_reuse: 'Token sesi dipakai dua kali — kemungkinan disalin',
      login_lockout: 'Terlalu banyak percobaan masuk yang salah',
      mfa_lockout: 'Terlalu banyak kode dua langkah yang salah',
      webhook_signature_flood: 'Banyak kiriman webhook tanpa tanda tangan sah',
      bulk_contact_reveal: 'Banyak nomor pelanggan dibuka oleh satu orang',
      dsr_overdue: 'Permintaan data pelanggan lewat batas waktu',
    } as Record<string, string>,
    clock: {
      not_applicable: 'Tidak perlu lapor',
      running: 'Batas lapor berjalan',
      due_soon: 'Kurang dari 12 jam',
      overdue: 'LEWAT BATAS',
      notified: 'Sudah dilaporkan',
    } as Record<string, string>,
    ack: 'Tandai sudah dibaca',
    reported: 'Catat sudah dilaporkan',
    reportedHint: 'Tulis siapa yang sudah diberi tahu dan kapan',
    deadline: 'Batas lapor',

    signInTitle: 'Masukkan kode dari aplikasi',
    signInHelp: 'Buka aplikasi authenticator Anda dan ketik 6 angka yang muncul. Kalau HP Anda hilang, pakai salah satu kode cadangan.',
    signInSubmit: 'Lanjut',
    signInExpired: 'Waktunya habis. Masuk lagi dari awal.',
  },

  sales: {
    title: 'Penjualan',
    subtitle: 'Geser penjualan ke tahap berikutnya. Yang ada tanda oranye sudah lama tidak ada kabar.',
    inProgress: 'dalam proses',
    won: 'berhasil',
    quiet: 'lama diam',
    quietChip: 'Lama diam',
    wonChip: 'Berhasil',
    lostChip: 'Batal',
    moveTo: 'Pindahkan ke',
    empty: 'Kosong',
    moveFailed: 'Gagal memindahkan',
    autoNote: 'Tahap pindah sendiri kalau pelanggan sudah bayar atau membuka penawaran.',
    noneYet: 'Belum ada penjualan',
    noneYetHelp: 'Penjualan muncul di sini setelah dibuat dari sebuah obrolan.',
  },

  dealDetail: {
    back: 'Penjualan',
    summary: 'Ringkasan',
    amount: 'Nilai',
    stage: 'Tahap',
    contact: 'Pelanggan',
    owner: 'Pemilik',
    noOwner: 'Belum ada',
    created: 'Dibuat',
    expectedClose: 'Target Penutupan',
    noExpectedClose: 'Belum ditentukan',
    notes: 'Catatan',
    notesPlaceholder: 'Tulis catatan soal deal ini — apa yang pelanggan bilang, kenapa macet, apa langkah berikutnya…',
    save: 'Simpan',
    saving: 'Menyimpan…',
    saved: 'Tersimpan.',
    failed: 'Gagal menyimpan',
    relatedOrders: 'Pesanan Terkait',
    noOrders: 'Belum ada pesanan dari deal ini.',
    activity: 'Riwayat Aktivitas',
    noActivity: 'Belum ada aktivitas.',
    openChip: 'Berjalan',
    lostReason: 'Alasan batal',
    notFound: 'Deal ini tidak ditemukan — mungkin sudah dihapus.',
  },

  team: {
    title: 'Tim',
    subtitle: 'Siapa saja yang bisa masuk, dan apa yang boleh mereka lakukan.',
    people: 'orang',
    person: 'Orang',
    role: 'Peran',
    whatTheyCanDo: 'Boleh melakukan apa',
    lastSeen: 'Terakhir masuk',
    you: 'Anda',
    add: 'Tambah orang',
    addName: 'Nama',
    addEmail: 'Email',
    addRole: 'Peran',
    addPassword: 'Kata sandi sementara',
    addPasswordHint: 'minimal 12 huruf',
    addSubmit: 'Tambahkan',
    adding: 'Menambahkan…',
    added: 'Sudah ditambahkan. Minta dia ganti kata sandi setelah masuk pertama kali.',
    passwordShort: 'Kata sandi sementara minimal 12 huruf',
    addFailed: 'Gagal menambahkan orang',
    onlyAdmin: 'Hanya Pemilik atau Admin yang bisa menambah orang.',
    auditNote: 'Setiap penambahan tercatat di Riwayat.',
  },

  settings: {
    title: 'Pengaturan',
    tabBill: 'Tagihan',
    tabHistory: 'Riwayat',

    usageTitle: 'Pemakaian bulan ini',
    usageSubtitle: 'Yang Anda bayar adalah jumlah obrolan, bukan jumlah pesan.',
    plan: 'Paket',
    chats: 'Obrolan',
    ofIncluded: 'dari',
    included: 'yang termasuk paket',
    autoReplies: 'Balasan otomatis',
    extra: 'Biaya tambahan',
    insidePlan: 'Masih di dalam paket',
    beyondPlan: 'lebih dari jatah paket',
    estimate: 'Perkiraan tagihan',
    exVat: 'belum termasuk PPN',
    thisMonth: 'Rincian bulan ini',
    line: 'Keterangan',
    qty: 'Jumlah',
    amount: 'Nilai',
    planLine: 'Paket',
    extraLine: 'Obrolan lebih dari jatah',
    metaLine: 'Biaya WhatsApp',
    metaNote: 'Ditagih Meta, kami teruskan apa adanya tanpa tambahan',
    plans: 'Pilihan paket',
    plansNote: 'Makin banyak obrolan, makin murah harga per obrolannya.',
    current: 'Paket Anda',
    suggested: 'Lebih hemat',
    perMonth: 'Per bulan',
    perChat: 'Per obrolan',
    numbers: 'Nomor WA',
    seats: 'Akun tim',
    extraPerChat: 'Kelebihan per obrolan',
    upgradeTitle: 'Bisa lebih hemat',
    upgradeBody: (plan: string, over: string) =>
      `Pemakaian Anda sudah lewat jatah paket. Naik ke paket ${plan} lebih murah daripada bayar kelebihan ${over}. Kami naikkan otomatis, bukan menagih selisihnya.`,
    countedHow: 'Cara hitungnya',
    countedHowBody:
      'Satu pelanggan yang chat dihitung 1 obrolan untuk 24 jam ke depan — mau dia kirim 2 pesan atau 50 pesan, tetap 1. Kalau dia chat lagi tiga hari kemudian, baru dihitung lagi.',

    invoices: 'Tagihan dari Kirana',
    invoicesNote: 'Ini tagihan toko Anda ke Kirana. Pembayaran lewat transfer bank.',
    invoicesEmpty: 'Belum ada tagihan. Tagihan pertama terbit di akhir periode.',
    invNumber: 'Nomor',
    invIssued: 'Terbit',
    invDue: 'Jatuh tempo',
    invTotal: 'Total',
    invStatus: 'Status',
    invOutstanding: 'Belum dibayar',
    invStatuses: {
      draft: 'Draf', issued: 'Menunggu bayar', paid: 'Lunas',
      overdue: 'Lewat jatuh tempo', void: 'Dibatalkan', written_off: 'Dihapusbukukan',
    } as Record<string, string>,
    markPaid: 'Tandai lunas',
    markPaidHint: 'Nomor referensi transfer',
    invFailed: 'Gagal menyimpan pembayaran',
    invPpn: 'termasuk PPN',

    historyTitle: 'Riwayat',
    historySubtitle: 'Catatan semua yang pernah terjadi. Tidak bisa diubah atau dihapus oleh siapa pun.',
    intact: 'Catatan utuh',
    broken: 'Catatan pernah diubah',
    what: 'Kegiatan',
    who: 'Oleh',
    detail: 'Rincian',
    when: 'Kapan',
    noHistory: 'Belum ada catatan.',
  },

  /** Machine event names, said in words. The raw name stays visible underneath. */
  events: {
    'auth.login': 'Masuk ke akun',
    'auth.logout': 'Keluar dari akun',
    'auth.refresh_reuse_detected': 'Sesi mencurigakan diblokir',
    'message.sent': 'Kirim pesan',
    'conversation.assigned': 'Obrolan dibagi ke orang',
    'conversation.resolved': 'Obrolan ditandai selesai',
    'deal.created': 'Penjualan dibuat',
    'deal.moved': 'Penjualan pindah tahap',
    'deal.updated': 'Detail deal diperbarui',
    'order.confirmed': 'Pesanan dikunci, menunggu bayar',
    'order.paid_manually': 'Pesanan ditandai dibayar',
    'order.fulfilled': 'Pesanan ditandai terkirim',
    'order.released': 'Pesanan dibatalkan',
    'member.invited': 'Anggota tim ditambah',
    'user.created': 'Anggota tim dibuat',
    'channel.connected': 'Saluran chat disambungkan',
    'channel.disconnected': 'Saluran chat diputus',
    'tenant.provisioned': 'Akun toko dibuat',
    'billing.period_closed': 'Periode tagihan ditutup',
    'retention.purged': 'Data lama dihapus otomatis',
    'dsr.erasure.completed': 'Data pelanggan dihapus atas permintaan',
  } as Record<string, string>,

  /** Keys that show up in history details, said in words. */
  metaKeys: {
    role: 'peran', plan: 'paket', kind: 'jenis', slug: 'nama akun',
    assigneeId: 'ditugaskan ke', stageId: 'tahap', status: 'status',
    amountIdr: 'nilai', messageId: 'pesan', template: 'template',
    messagesRedacted: 'pesan dihapus', conversations: 'obrolan',
    subtotalIdr: 'subtotal', retentionDays: 'simpan (hari)',
    timelineDeleted: 'riwayat dihapus', outcome: 'hasil',
  } as Record<string, string>,

  actors: {
    user: 'Orang',
    api_key: 'Aplikasi lain',
    system: 'Sistem',
    support: 'Tim Kirana',
  } as Record<string, string>,

  channels: {
    whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger',
    tiktok: 'TikTok', telegram: 'Telegram', tokopedia: 'Tokopedia',
    shopee: 'Shopee', email: 'Email', webchat: 'Chat web', whatsapp_web: 'WhatsApp (manual)',
  } as Record<string, string>,

  statuses: {
    open: 'Berjalan', pending: 'Menunggu', snoozed: 'Ditunda', resolved: 'Selesai',
  } as Record<string, string>,

  waBridge: {
    title: 'Chat WA',
    subtitle: 'Chat langsung dari nomor WhatsApp pribadi Anda, dipindai lewat kode QR — bukan nomor bisnis resmi.',
    warning:
      'Ini memakai WhatsApp Web, bukan jalur resmi Meta. WhatsApp bisa memblokir nomor yang dipakai kirim pesan massal atau balasan otomatis berlebihan. Cocok untuk chat manual dulu.',
    sessions: 'Nomor tersambung',
    addNumber: 'Sambungkan nomor baru',
    namePlaceholder: 'Nama nomor ini, misal: WA Toko 1',
    connect: 'Sambungkan',
    connecting: 'Menyambungkan…',
    cancel: 'Batal',
    scanQr: 'Kode QR untuk disambungkan',
    scanHow: 'Buka WhatsApp di HP → Perangkat Tertaut → Tautkan Perangkat, arahkan kamera ke kode ini.',
    disconnect: 'Putuskan',
    delete: 'Hapus',
    deleteTitle: 'Hapus nomor ini?',
    deleteWarning: (name: string) =>
      `Ini akan menghapus "${name}" beserta semua riwayat percakapan dan pesannya secara permanen. Tindakan ini tidak bisa dibatalkan.`,
    deleteConfirm: 'Ya, hapus permanen',
    reconnect: 'Sambungkan ulang',
    manage: 'Kelola nomor',
    noSessions: 'Belum ada nomor WhatsApp yang tersambung.',
    failed: 'Gagal menyambungkan nomor',
    status: {
      starting: 'Memulai…', qr_pending: 'Menunggu dipindai', authenticated: 'Autentikasi berhasil',
      ready: 'Tersambung', disconnected: 'Terputus', logged_out: 'Diputuskan', error: 'Gagal',
      connecting: 'Menyambungkan', connected: 'Tersambung', disabled: 'Nonaktif',
    } as Record<string, string>,
  },

  waStatus: {
    title: 'Status Nomor',
    subtitle: 'Semua nomor WhatsApp yang tersambung, dan berapa chat yang masih menunggu dibalas di masing-masing.',
    code: 'Kode',
    number: 'Nomor',
    totalChats: 'Jumlah Chat',
    todayChats: 'Chat Hari Ini',
    lastActive: 'Terakhir Aktif',
    neverActive: 'Belum ada chat',
    status: 'Status',
    unanswered: 'Belum Dijawab',
    unansweredCount: (n: number) => n === 0 ? 'Tidak ada' : `${n} chat`,
    queue: 'Antrian',
    queueCount: (n: number) => n === 0 ? 'Kosong' : `${n} belum dipegang`,
    avgReply: 'Rata-rata Waktu Balas',
    avgReplyNone: 'Belum ada balasan',
    noNumbers: 'Belum ada nomor WhatsApp yang tersambung.',
  },

  agentPerformance: {
    title: 'Performa Agen',
    subtitle: 'Ringkasan kinerja tim membalas chat. Data contoh — belum tersambung ke angka asli.',
    dummyNote: 'Data contoh',

    statActive: 'Agen Aktif',
    statActiveDelta: 'sedang online',
    statAvgReply: 'Rata-rata Waktu Balas',
    statAvgReplyDelta: '-1 menit dari kemarin',
    statHandled: 'Obrolan Ditangani Hari Ini',
    statHandledDelta: '+9 dari kemarin',
    statResolution: 'Tingkat Penyelesaian',
    statResolutionDelta: '+3% dari minggu lalu',

    panelHandled: 'Obrolan Ditangani per Agen',
    panelResolution: 'Tingkat Penyelesaian per Agen',
    panelRings: 'Ringkasan Performa Tim',
    panelRingsNote: 'Tiap garis mewakili satu ukuran, dihitung dari pencapaian terhadap target.',
    ringChat: 'Chat',
    ringRespon: 'Respon',
    ringSpeed: 'Speed',
    panelRingsPerAgent: 'Skor Performa per Agen',
    panelRingsPerAgentNote: 'Sama seperti di atas, dipecah per agen. Angka di tengah adalah rata-rata ketiga ukuran.',
    ringScoreLabel: 'Skor',
    panelDetail: 'Detail Performa Agen',

    tableAgent: 'Agen',
    tableHandled: 'Ditangani',
    tableWaiting: 'Perlu Dibalas',
    tableAvgReply: 'Rata-rata Waktu Balas',
    tableResolution: 'Tingkat Penyelesaian',
    tableRating: 'Rating',
  },

  contact: {
    title: 'Contact',
    comingSoon: 'Halaman ini belum ada isinya.',
  },

  dashboard: {
    title: 'Dashboard',
    subtitle: 'Ringkasan toko Anda. Data contoh — belum tersambung ke angka asli.',
    dummyNote: 'Data contoh',

    statCustomers: 'Total Pelanggan',
    statCustomersDelta: '+12 minggu ini',
    statUnanswered: 'Obrolan Perlu Dibalas',
    statUnansweredDelta: '-3 dari kemarin',
    statSales: 'Penjualan Bulan Ini',
    statSalesDelta: '+18% dari bulan lalu',
    statReplyTime: 'Rata-rata Waktu Balas',
    statReplyTimeDelta: '-2 menit dari kemarin',

    panelDaily: 'Obrolan Masuk — 7 Hari Terakhir',
    panelChannels: 'Saluran Teraktif',
    panelPipeline: 'Pipa Penjualan',
    panelRecent: 'Pelanggan Terbaru',

    days: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'],

    tableName: 'Nama',
    tablePhone: 'Nomor',
    tableTag: 'Label',
    tableWhen: 'Ditambahkan',
  },

  customers: {
    title: 'Pelanggan',
    subtitle: 'Orang-orang yang sudah ditandai sebagai customer, dari chat maupun ditambah manual.',
    name: 'Nama',
    phone: 'Nomor',
    email: 'Email',
    tags: 'Label',
    tagsHint: 'Pisahkan dengan koma, misal: vip, grosir',
    address: 'Alamat',
    addressPlaceholder: 'Jalan, kota, kode pos',
    notes: 'Catatan',
    notesPlaceholder: 'Catatan internal soal pelanggan ini',
    lastSeen: 'Terakhir Aktif',
    chat: 'Chat',
    noChat: 'Belum ada obrolan dengan pelanggan ini',
    noCustomers: 'Belum ada pelanggan. Tandai dari halaman chat, atau tambah manual.',
    add: 'Tambah Pelanggan',
    edit: 'Edit',
    actions: 'Aksi',
    photoUpload: 'Unggah foto pelanggan',
    photoChange: 'Ubah foto',
    searchPlaceholder: 'Cari nama, nomor, atau label…',
    filters: 'Filters',
    groupBy: 'Group By',
    noFilters: 'Belum ada label untuk difilter',
    noGroup: 'Tidak dikelompokkan',
    groupByTag: 'Label',
    noLabel: 'Tanpa label',
    noMatches: 'Tidak ada pelanggan yang cocok dengan pencarian/filter ini.',
    newCustomer: 'Pelanggan Baru',
    namePlaceholder: 'Nama pelanggan',
    save: 'Simpan',
    saving: 'Menyimpan…',
    discard: 'Batal',
    delete: 'Hapus',
    deleteTitle: 'Hapus pelanggan ini?',
    deleteWarning: (name: string) =>
      `"${name}" akan disembunyikan dari daftar Pelanggan. Data dan riwayat chat-nya tetap tersimpan, tidak benar-benar hilang.`,
    deleteConfirm: 'Ya, hapus',
    phoneMaskedHint: 'Nomor disamarkan — cuma yang punya akses lihat nomor penuh yang bisa mengubahnya.',
    saved: 'Tersimpan',
    failed: 'Gagal menyimpan data pelanggan',
    notFound: 'Pelanggan ini tidak ditemukan — mungkin sudah dihapus.',
  },

  orders: {
    title: 'Pesanan',
    subtitle: 'Semua pesanan dari chat, mulai dari draf sampai terkirim.',
    searchPlaceholder: 'Cari kode pesanan, nama, atau nomor…',
    filterAll: 'Semua',
    filterDraft: 'Draf',
    filterAwaiting: 'Menunggu Bayar',
    filterPaid: 'Sudah Dibayar',
    filterFulfilled: 'Terkirim',
    filterCancelled: 'Dibatalkan',
    code: 'Kode',
    customer: 'Pelanggan',
    items: 'Item',
    itemsCount: (n: number) => `${n} item`,
    total: 'Total',
    area: 'Area Kirim',
    created: 'Dibuat',
    status: 'Status',
    actions: 'Aksi',
    statusLabel: {
      draft: 'Draf',
      awaiting_payment: 'Menunggu Bayar',
      paid: 'Sudah Dibayar',
      fulfilled: 'Terkirim',
      cancelled: 'Dibatalkan',
    } as Record<string, string>,
    markPaid: 'Tandai Dibayar',
    fulfill: 'Tandai Terkirim',
    cancel: 'Batalkan',
    cancelTitle: 'Batalkan pesanan ini?',
    cancelWarning: (code: string) =>
      `Pesanan "${code}" akan dibatalkan dan stok yang sudah dikunci dikembalikan. Tindakan ini tidak bisa dibatalkan.`,
    cancelConfirm: 'Ya, batalkan',
    discard: 'Tutup',
    noArea: '—',
    empty: 'Belum ada pesanan. Pesanan muncul di sini setelah dibuat dari sebuah obrolan.',
    noMatches: 'Tidak ada pesanan yang cocok dengan pencarian/filter ini.',
  },
};
