/**
 * Every word the user reads, in one file.
 *
 * Two rules were applied to all of it:
 *   1. Bahasa Indonesia, the way a shop supervisor in Jakarta actually talks —
 *      not translated software English.
 *   2. No jargon. "Overage" became "biaya tambahan", "resolve" became "tandai
 *      selesai", "conversation window" became "sudah lewat 24 jam". Where a rule
 *      comes from WhatsApp rather than from us, the copy says so, because a
 *      person who understands *why* stops being afraid of the button.
 *
 * Keeping it in one place means the plain-language pass can be reviewed by
 * someone who does not read React.
 */
export const t = {
  app: {
    name: 'Kirana',
    tagline: 'Semua chat pelanggan di satu tempat',
  },

  nav: {
    chats: 'Obrolan',
    sales: 'Penjualan',
    team: 'Tim',
    settings: 'Pengaturan',
    signOut: 'Keluar',
  },

  roles: {
    owner: 'Pemilik',
    admin: 'Admin',
    supervisor: 'Supervisor',
    agent: 'Agen',
    viewer: 'Hanya lihat',
  } as Record<string, string>,

  roleNote: {
    owner: 'Bisa semua, termasuk tagihan dan menutup akun',
    admin: 'Bisa semua kecuali tagihan',
    supervisor: 'Bisa buka semua obrolan, bagi tugas, dan lihat nomor lengkap',
    agent: 'Hanya obrolan miliknya atau yang belum dipegang. Nomor pelanggan disamarkan',
    viewer: 'Hanya bisa melihat, tidak bisa membalas',
  } as Record<string, string>,

  login: {
    title: 'Masuk ke akun toko Anda',
    subtitle: 'Pakai nama akun yang dibuat oleh admin Anda.',
    shop: 'Nama akun toko',
    shopHint: 'Contoh: toko-demo',
    email: 'Email',
    password: 'Kata sandi',
    submit: 'Masuk',
    demo: 'COBA DULU',
    expired: 'Sesi Anda habis. Silakan masuk lagi.',
    wrong: 'Email atau kata sandi tidak cocok',
    tooMany: 'Terlalu banyak percobaan. Tunggu beberapa menit.',
    offline: 'Tidak bisa menghubungi server',
    incomplete: 'Semua kolom harus diisi',
    stale: 'Halaman ini sudah kedaluwarsa. Muat ulang lalu coba lagi.',
  },

  chats: {
    title: 'Obrolan',
    subtitle: 'Balas pelanggan di sini. Yang ada tanda kuning belum dibalas.',
    filterAll: 'Semua',
    filterNeedsReply: 'Perlu dibalas',
    filterDone: 'Selesai',
    needsReply: 'Menunggu balasan Anda',
    nobodyYet: 'Belum dipegang',
    done: 'Selesai',
    unknown: 'Tanpa nama',
    emptyList: 'Tidak ada obrolan di sini.',
    pickOne: 'Pilih satu obrolan di kiri',
    pickOneHelp: 'Obrolan paling baru ada di atas. Tanda kuning berarti pelanggan sedang menunggu balasan Anda.',
    live: 'Otomatis segarkan',
    paused: 'Berhenti sementara',
    updated: 'Diperbarui',
    refreshing: 'Memuat…',

    takeIt: 'Saya yang tangani',
    handledBy: 'Ditangani oleh',
    assign: 'Simpan',
    markDone: 'Tandai selesai',
    reopen: 'Sudah selesai',
    noOne: 'Belum ada',

    canReplyFreely: 'Bisa balas bebas',
    templateOnly: 'Sudah lewat 24 jam',
    windowClosedTitle: 'Pelanggan ini terakhir chat lebih dari 24 jam lalu',
    windowClosedBody:
      'Ini aturan dari WhatsApp, bukan dari kami: kalau sudah lewat 24 jam, balasan harus memakai pesan template yang sudah disetujui Meta. Tulis nama templatenya di bawah, lalu kirim.',
    templateName: 'Nama template',
    templateNameHint: 'contoh: konfirmasi_pesanan',
    writeReply: 'Tulis balasan…',
    writeTemplate: 'Isi pesan template…',
    send: 'Kirim balasan',
    sendTemplate: 'Kirim template',
    sending: 'Mengirim…',
    emptyMessage: 'Tulis pesannya dulu',
    sendFailed: 'Pesan gagal dikirim',
    freeform: 'Masih dalam 24 jam — boleh balas bebas',

    sender: {
      contact: 'Pelanggan',
      agent: 'Anda / tim',
      autopilot: 'Dijawab otomatis',
      system: 'Sistem',
    } as Record<string, string>,

    redacted: 'sudah dihapus',
    noMessages: 'Belum ada pesan.',

    aboutCustomer: 'Tentang pelanggan',
    name: 'Nama',
    phone: 'Nomor HP',
    lastChat: 'Terakhir chat',
    autoReply: 'Balasan otomatis',
    handling: 'Penanganan',
    status: 'Status',
    ordersHere: 'Pesanan',
    noOrders: 'Belum ada pesanan dari chat ini.',
    orderStatus: {
      draft: 'Sedang disusun', awaiting_payment: 'Menunggu bayar',
      paid: 'Sudah dibayar', cancelled: 'Dibatalkan', fulfilled: 'Sudah dikirim',
    } as Record<string, string>,
    salesHere: 'Penjualan',
    noSales: 'Belum ada penjualan untuk pelanggan ini.',
    inProgress: 'dalam proses',
    billingNote:
      'Satu pelanggan dihitung 1 obrolan per 24 jam, berapa pun jumlah pesannya.',
  },

  autopilot: {
    ready: 'Balasan otomatis sudah disiapkan',
    confidence: 'yakin',
    explain: 'Ini belum terkirim. Baca dulu, baru putuskan.',
    use: 'Pakai & kirim',
    edit: 'Ubah dulu',
    sendEdited: 'Kirim yang sudah diubah',
    cancelEdit: 'Batal',
    discard: 'Abaikan',
    working: 'Sebentar…',
    failed: 'Gagal memproses balasan otomatis',

    title: 'Balasan otomatis',
    subtitle: 'Seberapa jauh robot boleh menjawab sendiri, dan dari katalog mana dia menjawab.',
    mode: 'Cara kerja',
    modeOff: 'Mati',
    modeOffNote: 'Tidak menyiapkan apa pun.',
    modeSuggest: 'Siapkan draf saja',
    modeSuggestNote: 'Robot menulis, orang yang menekan kirim. Mulai dari sini.',
    modeAuto: 'Balas sendiri',
    modeAutoNote: 'Robot langsung membalas, tapi hanya kalau semua pemeriksaan lolos.',
    save: 'Simpan',
    saved: 'Tersimpan.',
    guardTitle: 'Yang selalu diperiksa sebelum terkirim',
    guards: [
      'Harga harus ada di katalog. Angka karangan langsung ditahan.',
      'Tidak boleh menjanjikan diskon atau tanggal barang pasti sampai.',
      'Tidak boleh bilang stok ada kalau di katalog stoknya nol.',
      'Pelanggan yang komplain selalu diserahkan ke orang.',
      'Kalau robot ragu, orang yang menjawab.',
    ],
    capTitle: 'Batas aman',
    capBody: (n: number) =>
      `Maksimal ${n} balasan otomatis per jam untuk seluruh toko. Kalau chat membanjir, robot berhenti dan orang yang lanjut — supaya biaya tidak lari.`,
    capOff: 'Tidak ada batas jumlah balasan otomatis per jam.',
    stats: 'Sebulan terakhir',
    statPending: 'Menunggu diperiksa',
    statUsed: 'Dipakai apa adanya',
    statEdited: 'Dipakai setelah diubah',
    statAuto: 'Dikirim sendiri',
    statBlocked: 'Ditahan pemeriksaan',
    statDiscarded: 'Dibuang',
    catalogue: 'Katalog & aturan',
    catalogueNote: 'Robot hanya boleh menjawab dari daftar ini. Kalau tidak ada di sini, dia menyerahkan ke orang.',
    kind: 'Jenis',
    itemTitle: 'Nama',
    sku: 'Kode',
    price: 'Harga',
    stock: 'Stok',
    emptyCatalogue: 'Katalog masih kosong. Selama kosong, robot tidak akan menjawab sendiri.',
    kinds: { product: 'Produk', faq: 'Tanya jawab', policy: 'Aturan' } as Record<string, string>,
  },

  /** Why a draft was held back, in words a supervisor can act on. */
  guardReasons: {
    ungrounded_price: 'Harga tidak ada di katalog',
    discount_not_allowed: 'Menjanjikan diskon',
    delivery_promise_not_allowed: 'Menjanjikan tanggal sampai',
    unknown_sku: 'Menyebut produk yang tidak ada',
    out_of_stock_claim: 'Bilang ada padahal stok habis',
    too_long: 'Balasan kepanjangan',
    empty_reply: 'Balasan kosong',
    external_link: 'Ada tautan asing',
    escalation_keyword: 'Pelanggan sedang komplain',
    low_confidence: 'Robot kurang yakin',
    model_asked_for_human: 'Robot minta dibantu orang',
    model_refused: 'Robot menolak menjawab',
    mode_off: 'Balasan otomatis sedang mati',
    mode_suggest: 'Mode siapkan draf',
  } as Record<string, string>,

  catalogue: {
    title: 'Katalog',
    subtitle: 'Robot hanya boleh menjawab dari daftar ini. Isi yang rapi di sini = jawaban yang benar di chat.',
    products: 'Produk',
    productsNote: 'Harga dan stok di sini yang dipakai robot untuk menjawab dan membuat pesanan.',
    name: 'Nama barang',
    sku: 'Kode',
    skuHint: 'contoh: KML-01',
    price: 'Harga',
    stock: 'Stok',
    note: 'Catatan',
    noteHint: 'warna, bahan, ukuran…',
    save: 'Simpan',
    saving: 'Menyimpan…',
    remove: 'Hapus',
    add: 'Tambah produk',
    addNote: 'Tambah tanya jawab / aturan',
    emptyProducts: 'Belum ada produk. Selama kosong, robot menyerahkan semua chat ke orang.',
    notes: 'Tanya jawab & aturan',
    notesNote: 'Hal yang sering ditanya: retur, cara bayar, jam kirim. Robot memakai ini apa adanya.',
    noteTitle: 'Judul',
    noteBody: 'Isi',
    kind: 'Jenis',
    kindFaq: 'Tanya jawab',
    kindPolicy: 'Aturan',
    emptyNotes: 'Belum ada catatan.',
    shipping: 'Ongkir',
    shippingNote: 'Tanpa ini robot tidak bisa menghitung total pesanan. Pakai "default" untuk daerah lain.',
    area: 'Daerah',
    cost: 'Biaya',
    eta: 'Estimasi hari',
    emptyShipping: 'Belum ada ongkir. Robot tidak akan bisa mengunci pesanan.',
    failed: 'Gagal menyimpan',
    saved: 'Tersimpan.',
  },

  security: {
    title: 'Keamanan',
    subtitle: 'Lapisan kedua supaya kata sandi saja tidak cukup untuk masuk.',
    twoStep: 'Verifikasi dua langkah',
    offNow: 'Belum aktif',
    onNow: 'Aktif',
    why: 'Kalau kata sandi Anda bocor, orang itu tetap tidak bisa masuk tanpa HP Anda. Sangat dianjurkan untuk Pemilik dan Admin.',
    turnOn: 'Nyalakan',
    step1: 'Buka aplikasi Google Authenticator atau Authy, pilih tambah akun, lalu masukkan kode di bawah ini.',
    secretLabel: 'Kunci untuk aplikasi',
    orOpen: 'Atau buka tautan ini di HP',
    step2: 'Masukkan 6 angka yang muncul di aplikasi',
    codeLabel: 'Kode 6 angka',
    confirm: 'Aktifkan',
    working: 'Sebentar…',
    cancel: 'Batal',
    turnOff: 'Matikan',
    turnOffHint: 'Masukkan kode dari aplikasi untuk mematikan',
    backupTitle: 'Kode cadangan',
    backupNote: 'Simpan sekarang. Kode ini hanya muncul sekali, dan dipakai kalau HP Anda hilang. Satu kode sekali pakai.',
    backupLeft: (n: number) => `${n} kode cadangan tersisa`,
    codeWrong: 'Kode tidak cocok. Cek jam di HP Anda, lalu coba lagi.',
    failed: 'Gagal memproses',

    eventsTitle: 'Kejadian keamanan',
    eventsNote: 'Hal-hal yang perlu dilihat orang. Yang bertanda merah punya batas waktu lapor.',
    eventsEmpty: 'Belum ada kejadian. Ini kabar baik.',
    clocksRunning: (n: number) => `${n} perlu dilaporkan`,
    kinds: {
      audit_chain_broken: 'Catatan riwayat diubah dari luar aplikasi',
      cross_tenant_denied: 'Ada yang mencoba membuka data toko lain',
      refresh_token_reuse: 'Token sesi dipakai dua kali — kemungkinan disalin',
      login_lockout: 'Terlalu banyak percobaan masuk yang salah',
      mfa_lockout: 'Terlalu banyak kode dua langkah yang salah',
      webhook_signature_flood: 'Banyak kiriman webhook tanpa tanda tangan sah',
      bulk_contact_reveal: 'Banyak nomor pelanggan dibuka oleh satu orang',
      dsr_overdue: 'Permintaan data pelanggan lewat batas waktu',
    } as Record<string, string>,
    clock: {
      not_applicable: 'Tidak perlu lapor',
      running: 'Batas lapor berjalan',
      due_soon: 'Kurang dari 12 jam',
      overdue: 'LEWAT BATAS',
      notified: 'Sudah dilaporkan',
    } as Record<string, string>,
    ack: 'Tandai sudah dibaca',
    reported: 'Catat sudah dilaporkan',
    reportedHint: 'Tulis siapa yang sudah diberi tahu dan kapan',
    deadline: 'Batas lapor',

    signInTitle: 'Masukkan kode dari aplikasi',
    signInHelp: 'Buka aplikasi authenticator Anda dan ketik 6 angka yang muncul. Kalau HP Anda hilang, pakai salah satu kode cadangan.',
    signInSubmit: 'Lanjut',
    signInExpired: 'Waktunya habis. Masuk lagi dari awal.',
  },

  sales: {
    title: 'Penjualan',
    subtitle: 'Geser penjualan ke tahap berikutnya. Yang ada tanda oranye sudah lama tidak ada kabar.',
    inProgress: 'dalam proses',
    won: 'berhasil',
    quiet: 'lama diam',
    quietChip: 'Lama diam',
    wonChip: 'Berhasil',
    lostChip: 'Batal',
    moveTo: 'Pindahkan ke',
    empty: 'Kosong',
    moveFailed: 'Gagal memindahkan',
    autoNote: 'Tahap pindah sendiri kalau pelanggan sudah bayar atau membuka penawaran.',
    noneYet: 'Belum ada penjualan',
    noneYetHelp: 'Penjualan muncul di sini setelah dibuat dari sebuah obrolan.',
  },

  team: {
    title: 'Tim',
    subtitle: 'Siapa saja yang bisa masuk, dan apa yang boleh mereka lakukan.',
    people: 'orang',
    person: 'Orang',
    role: 'Peran',
    whatTheyCanDo: 'Boleh melakukan apa',
    lastSeen: 'Terakhir masuk',
    you: 'Anda',
    add: 'Tambah orang',
    addName: 'Nama',
    addEmail: 'Email',
    addRole: 'Peran',
    addPassword: 'Kata sandi sementara',
    addPasswordHint: 'minimal 12 huruf',
    addSubmit: 'Tambahkan',
    adding: 'Menambahkan…',
    added: 'Sudah ditambahkan. Minta dia ganti kata sandi setelah masuk pertama kali.',
    passwordShort: 'Kata sandi sementara minimal 12 huruf',
    addFailed: 'Gagal menambahkan orang',
    onlyAdmin: 'Hanya Pemilik atau Admin yang bisa menambah orang.',
    auditNote: 'Setiap penambahan tercatat di Riwayat.',
  },

  settings: {
    title: 'Pengaturan',
    tabBill: 'Tagihan',
    tabHistory: 'Riwayat',

    usageTitle: 'Pemakaian bulan ini',
    usageSubtitle: 'Yang Anda bayar adalah jumlah obrolan, bukan jumlah pesan.',
    plan: 'Paket',
    chats: 'Obrolan',
    ofIncluded: 'dari',
    included: 'yang termasuk paket',
    autoReplies: 'Balasan otomatis',
    extra: 'Biaya tambahan',
    insidePlan: 'Masih di dalam paket',
    beyondPlan: 'lebih dari jatah paket',
    estimate: 'Perkiraan tagihan',
    exVat: 'belum termasuk PPN',
    thisMonth: 'Rincian bulan ini',
    line: 'Keterangan',
    qty: 'Jumlah',
    amount: 'Nilai',
    planLine: 'Paket',
    extraLine: 'Obrolan lebih dari jatah',
    metaLine: 'Biaya WhatsApp',
    metaNote: 'Ditagih Meta, kami teruskan apa adanya tanpa tambahan',
    plans: 'Pilihan paket',
    plansNote: 'Makin banyak obrolan, makin murah harga per obrolannya.',
    current: 'Paket Anda',
    suggested: 'Lebih hemat',
    perMonth: 'Per bulan',
    perChat: 'Per obrolan',
    numbers: 'Nomor WA',
    seats: 'Akun tim',
    extraPerChat: 'Kelebihan per obrolan',
    upgradeTitle: 'Bisa lebih hemat',
    upgradeBody: (plan: string, over: string) =>
      `Pemakaian Anda sudah lewat jatah paket. Naik ke paket ${plan} lebih murah daripada bayar kelebihan ${over}. Kami naikkan otomatis, bukan menagih selisihnya.`,
    countedHow: 'Cara hitungnya',
    countedHowBody:
      'Satu pelanggan yang chat dihitung 1 obrolan untuk 24 jam ke depan — mau dia kirim 2 pesan atau 50 pesan, tetap 1. Kalau dia chat lagi tiga hari kemudian, baru dihitung lagi.',

    invoices: 'Tagihan dari Kirana',
    invoicesNote: 'Ini tagihan toko Anda ke Kirana. Pembayaran lewat transfer bank.',
    invoicesEmpty: 'Belum ada tagihan. Tagihan pertama terbit di akhir periode.',
    invNumber: 'Nomor',
    invIssued: 'Terbit',
    invDue: 'Jatuh tempo',
    invTotal: 'Total',
    invStatus: 'Status',
    invOutstanding: 'Belum dibayar',
    invStatuses: {
      draft: 'Draf', issued: 'Menunggu bayar', paid: 'Lunas',
      overdue: 'Lewat jatuh tempo', void: 'Dibatalkan', written_off: 'Dihapusbukukan',
    } as Record<string, string>,
    markPaid: 'Tandai lunas',
    markPaidHint: 'Nomor referensi transfer',
    invFailed: 'Gagal menyimpan pembayaran',
    invPpn: 'termasuk PPN',

    historyTitle: 'Riwayat',
    historySubtitle: 'Catatan semua yang pernah terjadi. Tidak bisa diubah atau dihapus oleh siapa pun.',
    intact: 'Catatan utuh',
    broken: 'Catatan pernah diubah',
    what: 'Kegiatan',
    who: 'Oleh',
    detail: 'Rincian',
    when: 'Kapan',
    noHistory: 'Belum ada catatan.',
  },

  /** Machine event names, said in words. The raw name stays visible underneath. */
  events: {
    'auth.login': 'Masuk ke akun',
    'auth.logout': 'Keluar dari akun',
    'auth.refresh_reuse_detected': 'Sesi mencurigakan diblokir',
    'message.sent': 'Kirim pesan',
    'conversation.assigned': 'Obrolan dibagi ke orang',
    'conversation.resolved': 'Obrolan ditandai selesai',
    'deal.created': 'Penjualan dibuat',
    'deal.moved': 'Penjualan pindah tahap',
    'member.invited': 'Anggota tim ditambah',
    'user.created': 'Anggota tim dibuat',
    'channel.connected': 'Saluran chat disambungkan',
    'tenant.provisioned': 'Akun toko dibuat',
    'billing.period_closed': 'Periode tagihan ditutup',
    'retention.purged': 'Data lama dihapus otomatis',
    'dsr.erasure.completed': 'Data pelanggan dihapus atas permintaan',
  } as Record<string, string>,

  /** Keys that show up in history details, said in words. */
  metaKeys: {
    role: 'peran', plan: 'paket', kind: 'jenis', slug: 'nama akun',
    assigneeId: 'ditugaskan ke', stageId: 'tahap', status: 'status',
    amountIdr: 'nilai', messageId: 'pesan', template: 'template',
    messagesRedacted: 'pesan dihapus', conversations: 'obrolan',
    subtotalIdr: 'subtotal', retentionDays: 'simpan (hari)',
    timelineDeleted: 'riwayat dihapus', outcome: 'hasil',
  } as Record<string, string>,

  actors: {
    user: 'Orang',
    api_key: 'Aplikasi lain',
    system: 'Sistem',
    support: 'Tim Kirana',
  } as Record<string, string>,

  channels: {
    whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger',
    tiktok: 'TikTok', telegram: 'Telegram', tokopedia: 'Tokopedia',
    shopee: 'Shopee', email: 'Email', webchat: 'Chat web',
  } as Record<string, string>,

  statuses: {
    open: 'Berjalan', pending: 'Menunggu', snoozed: 'Ditunda', resolved: 'Selesai',
  } as Record<string, string>,
};
