'use client';

import { useActionState } from 'react';
import { connectInstagramMeta, disconnectInstagramMeta, type ActionResult } from '@/app/(app)/actions';
import { t } from '@/lib/copy';
import { CsrfField } from '@/components/Csrf';
import type { IgMetaConnection } from '@/lib/api';

/**
 * The sanctioned counterpart to `InstagramBridgeForm` — a pasted Instagram
 * Graph API access token (generated by hand from the Meta App dashboard),
 * not a browser automation and not an OAuth dance. The token itself is the
 * credential; this form's only job is to hand it to the API for
 * verification and storage.
 */
export function InstagramMetaCard({ connection }: { connection: IgMetaConnection }) {
  const [connectState, connectAction, connecting] =
    useActionState<ActionResult | null, FormData>(connectInstagramMeta, null);
  const [disconnectState, disconnectAction, disconnecting] =
    useActionState<ActionResult | null, FormData>(disconnectInstagramMeta, null);

  return (
    <div className="panel">
      <header><h2>{t.instagramMeta.sectionTitle}</h2></header>
      <div className="body stack" style={{ gap: 14 }}>
        <p className="muted" style={{ maxWidth: '62ch', lineHeight: 1.6, margin: 0 }}>{t.instagramMeta.subtitle}</p>

        {connection.status === 'connected' ? (
          <>
            <p style={{ margin: 0, fontWeight: 600, color: 'var(--good)' }}>
              {t.instagramMeta.connectedAs(connection.igUsername ?? '—')}
            </p>
            <form action={disconnectAction}>
              <CsrfField />
              <button type="submit" className="btn ghost" style={{ color: 'var(--danger)' }} disabled={disconnecting}>
                {disconnecting ? t.instagramMeta.disconnecting : t.instagramMeta.disconnect}
              </button>
            </form>
            {disconnectState?.error ? <p className="error">{disconnectState.error}</p> : null}
          </>
        ) : (
          <form action={connectAction} className="stack" style={{ gap: 12 }}>
            <CsrfField />
            <div className="record-field">
              <label htmlFor="igm-accessToken">{t.instagramMeta.accessToken}</label>
              <input className="line-input" id="igm-accessToken" name="accessToken" type="password"
                     autoComplete="off" placeholder={t.instagramMeta.accessTokenPlaceholder} />
            </div>
            {connectState?.error ? (
              <p className="error" style={{ fontSize: 12.5 }}>{connectState.error}</p>
            ) : connection.status === 'error' && connection.lastError ? (
              <p className="error" style={{ fontSize: 12.5 }}>{connection.lastError}</p>
            ) : null}
            <div>
              <button type="submit" className="btn primary" disabled={connecting}>
                {connecting ? t.instagramMeta.connecting : t.instagramMeta.connect}
              </button>
            </div>
          </form>
        )}

        {connection.updatedAt ? (
          <p className="mono dim" style={{ fontSize: 12 }}>
            {t.instagramMeta.lastUpdated(new Date(connection.updatedAt).toLocaleString('id-ID'))}
          </p>
        ) : null}
      </div>
    </div>
  );
}
